### ISSUE TITLE
deviantART broken image files

### ISSUE THREAD

**Issue by Elytreus** [4pr0n/ripme#112]
The downloader works great most of the time, but once in a while it downloads broken images. The pictures can not be opened with any program and are in some cases just a few bytes big. If I download these images manually they are completely fine.

The files look like this:
![broken images](https://cloud.githubusercontent.com/assets/8593129/4096033/4c17bd3a-2fbc-11e4-966d-02f5889eebf8.PNG)

**Comment by rautamiekka** [comment]
I haven't ever encountered this ancient problem, and we're up to RipMe 1.5.5 nowadays, but I'm still on 1.5.2.

Window$ 7 Ultimate SP1 x64, Oracle Java SE 8 Update 144 x64, I've ripped dozens of entire galleries (which still are on the disk) and every so often sync my favs folders, no real problems.

**Comment by metaprime** [comment]
Yeah the dA ripper still has a lot of problems but I think we can probably close this one at this point. I've never seen it.
