### ISSUE TITLE
Instagram Rips Failing

### ISSUE THREAD

**Issue by ohhdemgirls** [4pr0n/ripme#129]
URL: `http://instagram.com/chloeariadne`
Screen: https://i.imgur.com/brgz8Rj.png
Version: v1.0.90

**Comment by 4pr0n** [comment]
Might've been a problem with iconosquare (what is used to fetch instagram rips).

Looks like it's working now for other accounts. `chloeariadne` is currently [a private account](http://iconosquare.com/chloeariadne). Error messaging could be nicer...

**Comment by 4pr0n** [comment]
Should be fixed. Reopen if there's still issues.
