### ISSUE TITLE
Ripme doesn't show at all?!

### ISSUE THREAD

**Issue by Gyan7** [4pr0n/ripme#131]
http://imgur.com/q3IaSub

I don't know why but I tried to open it today and this is what's happening. Re-installed java, system restore'd, I don't know what else to try, does anyone else have a solution?

**Comment by 4pr0n** [comment]
Someone else had the same issue.

```
[...] it worked great until today. I even tried the updated version and got the same result…basically I open it and it shows up on the lower right for a notification icon, but the app itself is just on the top left of the screen and minimized. Nothing I can figure out changes this. See this picture:

http://i.imgur.com/j8e69ew.png
```

What version of windows are you running? XP/Vista/7/8?

What version of Java are you running? 
You can go to `Start` > `Control Panel` > `add/remove programs` and find `Java` along with it's current version.

Other people complain that it worked before but stopped working all of the sudden.

**Comment by Gyan7** [comment]
Sorry for the late reply.

Windows 7.

Says Java 7 Update 71.

Basically, I've all but given up on this ever working again. If it does, it'd be amazing though, beats manually saving stuff any day.

**Comment by ravenstorm767** [comment]
as sad as it may seem, time to delete all ripme related files and re-download a new one.

thats what fixed it for me

**Comment by Neribr** [comment]
To any time traveller reading this thread:

1. download the .tar.gz file
2. import it on Netbeans
3. press F6

solved for me, here is a sample of the message on the console of Netbeans (it seems that some files were missing?)

------------------------------------------------------------------------
Building ripme 1.5.14
------------------------------------------------------------------------
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.5/maven-resources-plugin-2.5.pom
         
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.5/maven-resources-plugin-2.5.pom (7 KB at 19.2 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/19/maven-plugins-19.pom
           
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/19/maven-plugins-19.pom (11 KB at 29.3 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/19/maven-parent-19.pom
           
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/19/maven-parent-19.pom (25 KB at 64.3 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.5/maven-resources-plugin-2.5.jar
           
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.5/maven-resources-plugin-2.5.jar (26 KB at 66.5 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.1/maven-compiler-plugin-3.1.pom
           
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.1/maven-compiler-plugin-3.1.pom (10 KB at 27.6 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/24/maven-plugins-24.pom
           
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/24/maven-plugins-24.pom (11 KB at 29.0 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/23/maven-parent-23.pom
           
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/23/maven-parent-23.pom (32 KB at 81.6 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/apache/13/apache-13.pom
           
Downloaded: http://repo.maven.apache.org/maven2/org/apache/apache/13/apache-13.pom (14 KB at 37.5 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/junit/junit/3.8.1/junit-3.8.1.pom
            
Downloaded: http://repo.maven.apache.org/maven2/junit/junit/3.8.1/junit-3.8.1.pom (998 B at 2.7 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/jsoup/jsoup/1.8.1/jsoup-1.8.1.pom
         
Downloaded: http://repo.maven.apache.org/maven2/org/jsoup/jsoup/1.8.1/jsoup-1.8.1.pom (7 KB at 16.7 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/json/json/20140107/json-20140107.pom
         
Downloaded: http://repo.maven.apache.org/maven2/org/json/json/20140107/json-20140107.pom (5 KB at 11.4 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/commons-configuration/commons-configuration/1.7/commons-configuration-1.7.pom
           
Downloaded: http://repo.maven.apache.org/maven2/commons-configuration/commons-configuration/1.7/commons-configuration-1.7.pom (22 KB at 55.5 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/21/commons-parent-21.pom
           
Downloaded: http://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/21/commons-parent-21.pom (34 KB at 85.3 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.pom
           
Downloaded: http://repo.maven.apache.org/maven2/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.pom (13 KB at 33.4 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/9/commons-parent-9.pom
           
Downloaded: http://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/9/commons-parent-9.pom (22 KB at 55.9 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/apache/4/apache-4.pom
         
Downloaded: http://repo.maven.apache.org/maven2/org/apache/apache/4/apache-4.pom (5 KB at 12.2 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/commons-lang/commons-lang/2.6/commons-lang-2.6.pom
           
Downloaded: http://repo.maven.apache.org/maven2/commons-lang/commons-lang/2.6/commons-lang-2.6.pom (18 KB at 46.2 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/17/commons-parent-17.pom
           
Downloaded: http://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/17/commons-parent-17.pom (31 KB at 78.3 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/apache/7/apache-7.pom
           
Downloaded: http://repo.maven.apache.org/maven2/org/apache/apache/7/apache-7.pom (15 KB at 38.7 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.pom
           
Downloaded: http://repo.maven.apache.org/maven2/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.pom (18 KB at 48.5 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/5/commons-parent-5.pom
           
Downloaded: http://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/5/commons-parent-5.pom (16 KB at 42.3 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/commons-digester/commons-digester/1.8.1/commons-digester-1.8.1.pom
           
Downloaded: http://repo.maven.apache.org/maven2/commons-digester/commons-digester/1.8.1/commons-digester-1.8.1.pom (10 KB at 26.9 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/11/commons-parent-11.pom
           
Downloaded: http://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/11/commons-parent-11.pom (25 KB at 43.6 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/commons-beanutils/commons-beanutils/1.8.0/commons-beanutils-1.8.0.pom
           
Downloaded: http://repo.maven.apache.org/maven2/commons-beanutils/commons-beanutils/1.8.0/commons-beanutils-1.8.0.pom (11 KB at 27.9 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/commons-beanutils/commons-beanutils/1.8.3/commons-beanutils-1.8.3.pom
           
Downloaded: http://repo.maven.apache.org/maven2/commons-beanutils/commons-beanutils/1.8.3/commons-beanutils-1.8.3.pom (11 KB at 28.9 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/14/commons-parent-14.pom
           
Downloaded: http://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/14/commons-parent-14.pom (31 KB at 70.8 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.pom
           
Downloaded: http://repo.maven.apache.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.pom (22 KB at 52.4 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/commons-cli/commons-cli/1.2/commons-cli-1.2.pom
         
Downloaded: http://repo.maven.apache.org/maven2/commons-cli/commons-cli/1.2/commons-cli-1.2.pom (8 KB at 11.1 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/commons-io/commons-io/1.3.2/commons-io-1.3.2.pom
