### ISSUE TITLE
Request: Option to save descriptions, images, or both for some sites.

### ISSUE THREAD

**Issue by Wiiplay123** [4pr0n/ripme#136]
I was able to modify the source code for your program to grab deviantArt descriptions in addition to images. Could an option for this be put into a later version of RipMe?

To get the actual page URL for the description using the thumbnail element (which seems to work whether logged in or not), I used Jsoup.connect(thumb.parent().attr("href"))

To get the description from the document of the page, I used doc.select("div[class=text block]").

For the file name, I just did the thumbToFull(thumb.attr("src")) again and added a tiny bit of error checking for when the thumbnail and text are in the same thing for some reason at "fields.remove(4);" to catch IndexOutOfBoundsException when it's like that.

Thanks making such an awesome program! :+1:

**Comment by 4pr0n** [comment]
I merged the pull request & it went out in version `1.0.92` -- let me know if it works.
