### ISSUE TITLE
Reddit request rate limit being hit!

### ISSUE THREAD

**Issue by losipher** [4pr0n/ripme#145]
I have noticed when requesting a large number of user profiles that do not have many posts the program will trip the request rate limit set by Reddit's API. A possible fix would be to check 
X-Ratelimit-Remaining and if it zero then set a resume time given by X-Ratelimit-Reset. These API calls are all approximations so there is a possibility that users will still get a 429 HTTPRequest error. Another option would be to allow the user to enter reddit credentials to use the OAuth2 functionality that allows for twice as many requests per minute. Again this is not sure fire but it might help. I will try to tinker with this myself but I am new to Java.

**Comment by 4pr0n** [comment]
I can add a timeout (2000 ms) but it might work to just rip the `/user/<username>/submitted` URL which will only return posts & not comments.

**Comment by 4pr0n** [comment]
https://github.com/4pr0n/ripme/commit/afb7236db96b3ad34b48c59777bcd649f9da3dcc

Was pushed in `1.0.92`
