### ISSUE TITLE
Requests: Log only errors; allow re-ripping of individual items under history

### ISSUE THREAD

**Issue by Whocaresman** [4pr0n/ripme#147]
I think these options would be very useful.

I know I can't speak for everyone, but I think a majority of people would only look at a generated log to see what errors or images that RipMe missed. Currently, it writes everything including successes, so you have to single out all the issues that occurred during a rip process. It would be great if only issues or errors were written to a log.

I also wish there was an option that would allow you to only re-rip whatever URL/s were highlighted under the History tab. Currently, tou only have the option to re-rip everything, which is not ideal if you have a large history built up.

**Comment by 4pr0n** [comment]
In the future, please create separate issues for each request. It makes tracking issues much easier.

And it sucks when I go through a huge change (refactoring History) but still can't close this issue until the other features are done.

**Comment by 4pr0n** [comment]
Pushed both changes in `1.1.0`

Might add ability to set `Log Level` in configuration in the future.
