### ISSUE TITLE
will there be any ripper for vid.me

### ISSUE THREAD

**Issue by elwoodflame** [4pr0n/ripme#148]
I hope this is the right spot for this. Is there a way to get ripme to rip video from vid.me?

**Comment by Wiiplay123** [comment]
There's a pull request right now that adds that feature. Problem is, 4pr0n seems to have forgotten to look at his github for a few months so none of the pull requests are in the main branch yet. :c

**Comment by elwoodflame** [comment]
Ok Im new to this is there instructions to add the pull request?

**Comment by 4pr0n** [comment]
I've merged the pull request & pushed the changes to the latest version (`1.0.92`) which is available now.

`Configuration` > `Check for updates` to upgrade
