### ISSUE TITLE
Failed to download on everything

### ISSUE THREAD

**Issue by ravenstorm767** [4pr0n/ripme#150]
Ive been using this wonderful tool ever since it wasnt even a tool (browser version)

I have two of them "installed" one in my portable hard drive and one in my local PC, the one on my local hard drive that i use when in my office works fine but recently on the version of it on my home PC,
EVERY attempt to download comes up with the "failed to download" error string.

ive tried turing windows firewall on and off,uninstalling my new anti virus and even deleting the ripper and re-downloading a new one.nothing does the trick.

the problem started when around my old anti virus just uninstalled itself out of the blue and left all my programs unable to connect to the internet, i managed to get the complete remover for that program which fixed most of my programs. though after that, the ripper and some other small applications of mine just cant even connect anymore.

**Comment by 4pr0n** [comment]
It's likely there's an operating-system level proxy that you're using. There's been other issues about RipMe not respecting system proxies.

Leaving this open until I can setup a proxy on my own computer for testing.

**Comment by ravenstorm767** [comment]
@4pr0n incidentally, ive had my PC reformatted the other day(for different reasons), starting out with a fresh PC seems to have solved the problem.

all i can say is, stay away from norton antivirus
