### ISSUE TITLE
Select All in History

### ISSUE THREAD

**Issue by g1i1ch** [4pr0n/ripme#161]
It's a damn shame this isn't in the history dialog. I had a rip history a mile long, going through and checking each one to update is a huge pain. I also accidentally mistook the "clear" button to mean "clear the current selection" and accidentally lost all my history. Having a clear and delete button is a bit redundent. Simply replacing the "clear" button with a "select all" would be a whole lot more elegant, and used in unison with delete would clear the histories for those that want that.

**Comment by 4pr0n** [comment]
Right click an item in history. you should get options to `Check All`, `Check None`, `Check Selected` and `Uncheck Selected`

![screen shot 2015-01-25 at 4 24 48 pm](https://cloud.githubusercontent.com/assets/4276506/5894053/b431002c-a4ae-11e4-9b3b-f4c24279baef.png)
