### ISSUE TITLE
More 403 errors on DeviantArt

### ISSUE THREAD

**Issue by reddituser** [4pr0n/ripme#165]
Hi 4_pr0n,

I was able to rip most of the deviations from a few accounts, but I got about seventeen 403 errors. They came mostly at the end of the last user. I made a comment on the closed issue, but I couldn't reopen it (or just couldn't figure out how).

Oh, and just fyi, it seems like Cheeby is down. It redirects to some bogus site. Not really relevant to the topic, but just thought I'd mention.

**Comment by 4pr0n** [comment]
Reopened #159
