### ISSUE TITLE
Getting Red Error "Failed to download" on ImageFap

### ISSUE THREAD

**Issue by mrgrr26** [4pr0n/ripme#171]
Getting the red error message from imagefap "Failed to download".  Other sites work still, just imagfap is getting error.

**Comment by blakstone** [comment]
Same here.

**Comment by 4pr0n** [comment]
Yep. Imagefap started returning `702` HTTP status codes for images... which isn't a valid HTTP status code. I'm working on it.

**Comment by 4pr0n** [comment]
Nevermind, looks like @wraithfive fixed it. I'll push it out in version `1.1.7` soon

**Comment by 4pr0n** [comment]
Pushed out in `1.1.7`
