### ISSUE TITLE
Twitter rip missing some pictures (likely only getting first picture in a multi-picture post)

### ISSUE THREAD

**Issue by simplypro** [4pr0n/ripme#182]
hxxps://twitter.com/shau----nasky---exo (remove dashes) 38 photos, only rips 34, I think it rips the first picture in a multi-picture post

Is there any way to allow ripping of protected tweets account? through login of some sort perhaps?

**Comment by metaprime** [comment]
Provided example link (removed dashes) is 404 from Twitter. Could you provide an updated link?

It looks like there's two issues you're asking for here. Only ripping the first picture in a multi-picture post is most likely an actionable bug.

For logged-in features, that's probably not coming any time soon. That's a can of worms.

**Comment by metaprime** [comment]
Fixed in #478
