### ISSUE TITLE
Not ripping m.imgur.com galleries

### ISSUE THREAD

**Issue by rwoodpecker** [4pr0n/ripme#218]
Example: http://m.imgur.com/1ulB5Rr,jUnwFcS,anGsFuP,7PHezez,qv00CvM,IDMOWBs,RaZHrtm linked from profile https://www.reddit.com/user/Xx88xXy/submitted/

It will only rip the first picture and ignore the rest, despite them showing up on imgur a album.

**Comment by 4pr0n** [comment]
Thanks for the example URL!

I think I fixed this in the latest version.
