### ISSUE TITLE
The problem with downloading of deviantART

### ISSUE THREAD

**Issue by Jar4ek** [4pr0n/ripme#221]
Hi, We write about it because I encountered a problem.
Namely RipMe does not charge any photos from the deviantART, images that are not labeled as offensive or photos on which it is applied filter the view. Here, I give a link about that I mean.

Link : http://agnes-z-garbledville.deviantart.com/gallery/?catpath=/

Namely, the point here is that RipMe has collected only 126 photos and the rest no longer be able to download only downloaded image as a text file which takes only a few bytes.
It also gives the log I received from downloading the portal deviantART.

Log: https://pastebin.com/kbjRsS1N

Thank you in advance for solving this problem.

Best Regards Jarek.

**Comment by micnorian14** [comment]
I repeated your steps but could not reproduce the problem. Reviewing it I believe you may have mistaken one URL for another. 

When ripping all of a DA gallery you need to make sure the URL you use is the one for "All" images from the left side pane. By default when you select "galleries" on someone's DA profile you will land on their "featured" page.
ie: http://agnes-z-garbledville.deviantart.com/gallery/
Which only has say a few hundred

When what you want to rip is the "All" page url.
ie: http://agnes-z-garbledville.deviantart.com/gallery/?catpath=/
Which has several thousand! 

You can also rip specific albums by selecting them and using that specific URL, however they will break if renamed or moved in the future. 
ie: http://agnes-z-garbledville.deviantart.com/gallery/45661696/Agnes-and-her-friends
Which is still a lot but not several thousand. I think. 

The annoying text files get downloaded regardless - they are the post or subtext to each post. It's nice to have it go along with an image. I still can't find a way to ignore them - it is a waste of bandwidth and file space for me.

**Comment by 4pr0n** [comment]
> The annoying text files get downloaded regardless

You can now disable fetching descriptions in the Options: `Save descriptions` Defaults to "on"
