### ISSUE TITLE
RipMe: Not working anymore (with DeviantArt)?

### ISSUE THREAD

**Issue by faizo** [4pr0n/ripme#225]
Tried with the latest version both of java and firefox. With a DeviantArt page URL, I got this message: 
'Can´t rip this URL: com.rarchives.ripme.ripper.rippers (null) does not appear to be a valid package' Can you help me? (RipMe v1.1.8)

![ripme error](https://cloud.githubusercontent.com/assets/12936004/8206795/ee473e3e-14fc-11e5-93b6-2fd5c877463f.PNG)

**Comment by artaeun** [comment]
my guess is that's a problem on your end. I even managed to download the whole gallery without any problems

![image](https://cloud.githubusercontent.com/assets/6439106/8214886/aa45f876-152c-11e5-80c9-f0af9ba9bfd9.png)

**Comment by faizo** [comment]
Win8.1 64bit maybe? Seems like you have Win7

**Comment by faizo** [comment]
Downloaded the .jar again. working now. Didn´t change anything, weird.

**Comment by metaprime** [comment]
Looks like there's no action to take here. Closing.
