### ISSUE TITLE
Download?

### ISSUE THREAD

**Issue by ghost** [4pr0n/ripme#250]
The link for the download doesn't work anymore.

**Comment by version365** [comment]
Use this link...

[**ripme 1.2.0**](https://drive.google.com/open?id=0B8y8VXCkHetWRVQ1UHk3Zk15Zmc)

**Comment by Hrxn** [comment]
Which link do yo mean?

This one? http://rarchives.com/ripme.jar

Seems to work for me..

Don't know about the version, though

**Comment by metaprime** [comment]
http://rip.rarchives.com/
