### ISSUE TITLE
Is it possible to run this with command line arguments?

### ISSUE THREAD

**Issue by lostes** [4pr0n/ripme#256]
Is it possible to run this program with command line arguments?

For example the following shortcut:
ripme.jar -http://reddit.com/r/cats -C:\Downloads\

would download the pics and save it to the given location. If not is it possible to add this feature? It would save me a lot of time because I'm downloading from the same locations.

Thanks for this great tool btw!

**Comment by jackusm** [comment]
https://github.com/4pr0n/ripme/wiki/How-To-Run-RipMe
And I'm pretty sure you can edit "rip.properties" to set a download location

**Comment by lostes** [comment]
I looked through rip.properties but I couldn't find it. Also looked through some other files but find anything there either.

Any have an idea of in which file the download location can be set?

**Comment by CataBasic** [comment]
In rip.properties write down this line (if there isn't yet):
rips.directory = C:\\Downloads

I don't really know why it needs 2 backslashes instead of one...

**Comment by 4pr0n** [comment]
The `-h` help option shows the arguments:

```
$ java -jar ripme-1.2.0-jar-with-dependencies.jar -h
Loaded rip.properties
Loaded log4j.properties
Initialized ripme v1.2.0
usage: java -jar ripme.jar [OPTIONS]
 -4,--skip404               Don't retry after a 404 (not found) error
 -D,--nosaveorder           Don't save order of images
 -d,--saveorder             Save the order of images in album
 -h,--help                  Print the help
 -l,--ripsdirectory <arg>   Rips Directory (Default: ./rips)
 -r,--rerip                 Re-rip all ripped albums
 -R,--rerip-selected        Re-rip all selected albums
 -t,--threads <arg>         Number of download threads per rip
 -u,--url <arg>             URL of album to rip
 -w,--overwrite             Overwrite existing files
```

Notice `-u` is for the URL and `-l` is for the download location. So you can save the rips wherever `-l` points to, e.g.:

```bash
java -jar ripme.jar -u "http://imgur.com/a/UWEBF" -l "C:\Users\yourusername\Downloads"
```
