### ISSUE TITLE
Development blocked

### ISSUE THREAD

**Issue by 4pr0n** [4pr0n/ripme#258]
I dropped water on my laptop and now my laptop won't turn on. 

I won't be able to work on RipMe until I get a new laptop which may take a while. 

I can't merge pull requests without testing them first, either.

So hang tight for a few weeks/months.

Sorry, everybody.

**Comment by lostes** [comment]
Oh man that sucks. Are you accepting (small) donations towards getting a new laptop?

**Comment by Hrxn** [comment]
Yeah, sorry to hear that...

How does one even survive without an usable computer? ;-)

I agree, can we alleviate this unbearable situation in any way?
What do folks use nowadays? This Patron? Patreon? Do you have that?

Or just via Paypal, maybe...

**Comment by allysontits** [comment]
Sorry to hear about your laptop, that really sucks. Thanks for keeping us updated. We'll all be looking forward to when you can continue development, but don't be sorry for the delay! The fact that your laptop got ruined is a lot worse/more important than development being put on hold for a while. Thank you again for all of the work you've put into this, and good luck with being able to get a new laptop soon.

**Comment by 4pr0n** [comment]
Still no dev machine. I just merged a bunch of pull requests. Hopefully I can build a jar and release the latest version soon.

**Comment by Hrxn** [comment]
Great to hear.
Keep your chin up!

**Comment by 4pr0n** [comment]
Found a machine to build/push code on. I just pushed v1.2.1. Forgot to make a backup of v1.2.0, so save it before upgrading.

Last version I have saved is v1.1.9 which can be found at http://www.rarchives.com/ripme.backups/ripme.jar.1.1.9

**Comment by Hrxn** [comment]
Time to open the champagne!  ;-)

**Comment by 4pr0n** [comment]
I'm guessing the newest version (with all the pull-requests) is working, so I'll close this out.
