### ISSUE TITLE
ripme will not maximize

### ISSUE THREAD

**Issue by evc1234** [4pr0n/ripme#263]
Hello,

First of all thank you for the program! Second of all, it appears that ripme does not want to maximize? I can open it and it will show in my taskbar, I can open the aboutme etc but when it is fully maximized it is the tiniest size possible and the maximize button is greyed out and unable to be used.

I am on windows 7.

Any ideas? Thanks.

**Comment by evc1234** [comment]
I should add that this is on a completely fresh install.

**Comment by wpw** [comment]
Things to try:
1) Make sure you run the program from it's location directly. No shortcuts, search results windows, etc.
2) Delete the history and properties files. Back them up first just in case.

**Comment by i-cant-git** [comment]
Ripme should allow to maximize, History page is so small, I can't even see the URLs.

**Comment by metaprime** [comment]
Duplicate of #306

**Comment by metaprime** [comment]
#371
