### ISSUE TITLE
Gfycat links no longer working.

### ISSUE THREAD

**Issue by FrootiousLoopious** [4pr0n/ripme#269]
Whenever ripme now comes across a gfycat link it spits out this error: "Could not find source#mp4source at http://gfycat.com/"(insert final part of link here). This happens on all gfycat links and has happened since the gfycat 'update'. Also, if you are downloading from a subreddit that contains gfycat links now, it simply skips them entirely. I just would like to know if anyone else is experiencing similar issues and if this will get fixed in the future.

**Comment by masteraaran** [comment]
Having the same issue over here as well.

**Comment by dwhenderson** [comment]
Gfycat doc element was altered.  

In 
src/main/java/com/rarchives/ripme/ripper/rippers/video/GfycatRipper.java
@line 68

alter mp4source to mp4Source
or you may replace it with webmSource if you'd prefer to download that format instead.
Rebuild binary. Gfycat works again.

**Comment by Hrxn** [comment]
Build binary..

Oh my. What do you need? JRE? JDK? Eclipse? Or just Maven?

**Comment by dwhenderson** [comment]
Follow build directions using Maven on front page or in README.


Darren W. Henderson
Database Administrator
University of Kentucky
Center for Clinical and Translational Science
182 Bio-Pharmacy Complex 
789 S Limestone 
Lexington, KY 40536
W:(859) 323-7146
darren.henderson@uky.edu


-----Original Message-----

**Comment by Hrxn** [comment]
I know, this was just, well frustration, because of that 'Oh no I don't want to install all that crap again!"-feeling.

BTW, you replied via mail and with full signature showing, just wanted to let you know..

**Comment by dwhenderson** [comment]
Thanks for looking out.

**Comment by FrootiousLoopious** [comment]
Thank you so much dwhenderson, just did what you said and it works perfectly. Thanks again man.

**Comment by Hrxn** [comment]
BTW, what are the differences here between the .mp4 and .webm format? Did someone check?
Can't do it myself right now, I'm at a 'work' laptop.

Isn't .webm better now? AFAIK, YouTube uses the .webm container for their highest quality DASH streaming formats.
