### ISSUE TITLE
deviant art downloading .rar and .zip files

### ISSUE THREAD

**Issue by mommy742** [4pr0n/ripme#272]
so far as i can find for some reason it makes prints from devian art either into zip files, regualr files, or .rar files randomly. help?

**Comment by 4pr0n** [comment]
Can you provide a sample link (URL) that reproduces this issue?

**Comment by mommy742** [comment]
jsut do my gallery at http://mommy247.deviantart.com/favourites/ or just
use http://mommy247.deviantart.com/art/Feuersbrunst-108054629 it downloads
a rar and i cant find a way to open it so far.

**Comment by 4pr0n** [comment]
Tried it on the "favourites" URL and yea, reproduced it. Logs show

```
Attempting to get full size image from http://gucken.deviantart.com/art/Feuersbrunst-108054629

Found download page: http://www.deviantart.com/download/108054629/feuersbrunst_by_gucken-d1sbzhh.rar?token=7cf85b802e4bb094ee8c433a1e4635c0b54f67b0&ts=1450642273
```

So DeviantArt is giving a .rar to download it.

The download button on [Feuersbrunst](http://gucken.deviantart.com/art/Feuersbrunst-108054629) says:
`Download`
`RAR download, 2.2MB`

Looks like you'll have to manually extract RAR files using some tool like [7-Zip](http://www.7-zip.org/) (Windows/Linux, Free) or [Keka](http://www.kekaosx.com/en/) (Mac/OSX, Free).

I can't think of a simple way for the ripper to detect RAR files and extract them automatically.  For that example, the RAR contains a bunch of images and a "ReadMe"; it would require a significant effort to get the Ripper to support deviantart RAR files.

**Comment by metaprime** [comment]
No action to take on this bug. The content was a compressed file, and it downloads correctly. User needs to have the correct software to interact with the downloaded content.
