### ISSUE TITLE
realself.com Ripper

### ISSUE THREAD

**Issue by MelonMusk** [4pr0n/ripme#273]
Hi. Apologies if this is not the proper procedure for requesting a new feature/ripper but I'm not familiar with the protocol here.

Would it be possible to have a ripper for realself.com albums?

Thanks heaps!

**Comment by Hrxn** [comment]
This is the proper procedure, but the project is currently dormant..

**Comment by lostes** [comment]
Provide an example album for the dev(s)

**Comment by MelonMusk** [comment]
Example album: https://www.realself.com/review/miami-fl-breast-implants-pre-op-breast-augmentation-and-preparations#media-review-822974-image-201984

**Comment by MelonMusk** [comment]
Sorry... Any update on this please?

**Comment by metaprime** [comment]
Tagging #8 so it shows up in the request list. Closing this issue.
