### ISSUE TITLE
sex.com Ripper

### ISSUE THREAD

**Issue by ghost** [4pr0n/ripme#274]
I don't know if any of you use this site, but it's got a lot of galleries that could be ripped. I read that development is currently on hold, but if you are looking for a site to add, this would be great.

**Comment by 4pr0n** [comment]
> it's got a lot of galleries that could be ripped
Sample URL?

**Comment by scavault** [comment]
http://www.sex.com/user/barrel2/young-tits/

The main page has links to various galleries. Here's one I found.

**Comment by metaprime** [comment]
Please use #8 for site requests.

**Comment by metaprime** [comment]
Could also have user pages with all galleries ripped:
http://www.sex.com/user/barrel2/

Individual image pages:
http://www.sex.com/pin/42722667-anal-after-class/

**Comment by metaprime** [comment]
Another set of examples:
http://www.sex.com/user/betheking/
http://www.sex.com/user/betheking/my-favorite-boobs/
http://www.sex.com/pin/54248363-suck-em/
