### ISSUE TITLE
xHamster: urls with language prefix aren't parsed

### ISSUE THREAD

**Issue by cm-mc** [4pr0n/ripme#276]
xHamster is now (for a while) using language specific urls, so users for across the world are diverted to http(s)://XX.xhamster.com/..., instead of the original http(s)://(www.)xhamster.com/...
Ripme can't rip these urls, which means having to either manually edit every single url pasted or copying and pasting just the "common" part of the url.

**Comment by 4pr0n** [comment]
Should work now in latest v1.2.3

**Comment by cm-mc** [comment]
not working in 1.2.8
