### ISSUE TITLE
500px not downloading all the files (I think it's skipping the NSFW ones)

### ISSUE THREAD

**Issue by anonimo402** [4pr0n/ripme#278]
>DEBUG ripper.AbstractRipper .rip() Found image url #2: https://500px.com/graphics/nude/img_3.png
>INFO  ripper.AbstractRipper .addURLToDownload() [!] Skipping https://500px.com/graphics/nude/img_3.png -- already attempted: C:\Users\username\Desktop\Fedor\nuevas\500px_fedorshmidt\graphics.jpg

I've attached the log.

[log.txt](https://github.com/4pr0n/ripme/files/70039/log.txt)

**Comment by 4pr0n** [comment]
Whoops looks like the change in #260 broke it. I'll look at fixing it.
