### ISSUE TITLE
can i remove the last update and use 1.2.4

### ISSUE THREAD

**Issue by timthebuktu** [4pr0n/ripme#280]
Hello
I can not find the older Versions of RIPME. With Version 1.2.4 was 500px complete loadet and i wish use the older Version of RIPME. Where i can find older RIPME Files?
Thanks
Tim

**Comment by lostes** [comment]
Unless someone has an older version in their computer you might be out of luck. I have version 1.069,1.086 and 1.18 if you're interested.

**Comment by anonimo402** [comment]
I have these:
1.2.0
1.2.6

**Comment by timthebuktu** [comment]
Hi anonimo402
1.2.0 and 1.2.6 is top for me
can you send the files to me?

Thanks

**Comment by anonimo402** [comment]
Here you go:

https://www.dropbox.com/sh/c6dvhi3sxqo4mj1/AAAx0_-fLNWRle3mQ4zf1OQPa?dl=0

**Comment by timthebuktu** [comment]
Thanks for the files and have a good time
Tim
