### ISSUE TITLE
Imgur galleries only downloading 10 pictures

### ISSUE THREAD

**Issue by IT6uru** [4pr0n/ripme#284]

**Comment by DeiusShrab** [comment]
Imgur has limited large galleries to only showing 10 pictures at a time, with a 'Load remaining X images' javascript link at the bottom

**Comment by Hrxn** [comment]
Can confirm, guess they changed something on their API recently, because it did work not long ago..

Now you'll only get the first 10 elements of an album, the rest is loaded dynamically via Ajax in the browser and not present in the initial HTML.

**Comment by Zintax** [comment]
Is there any work around on this? Quite a few galleries id like to grab still...

**Comment by Hrxn** [comment]
I don't know about their API changes, but this URL still works:

http://imgur.com/ajaxalbums/getimages/kGQT3/hit.json?all=true

`http://imgur.com/ajaxalbums/getimages/12345/hit.json?all=true`
Would get you the data for:
imgur.com/a/12345

Just replace the ID part (length: 5) with the album you want

You can build direct links from the data within that JSON, and it is possible to automate this, but I haven't seen it yet.

**Comment by metaprime** [comment]
See also #266 and #300

**Comment by metaprime** [comment]
This issue seems fixed.
