### ISSUE TITLE
Fgts.jp functionality seems broken again

### ISSUE THREAD

**Issue by newageboi** [4pr0n/ripme#295]
"Downloading http://fgts.jp/soc/thread/23063024/
Rip complete, saved to E:\Program Files (x86)\LOLReplay\loc\anonib\rips\fgts_soc_23063024
Failed to load http://fgts.jp/soc/thread/23063024/ after 1 attempts"

**Comment by cyian-1756** [comment]
The site now redirects to what looks like a generic spam site so I assume this can be closed

**Comment by metaprime** [comment]
Yes, it looks like the site is down and gone, maybe for good. If it comes back, existing functionality might still work. I'll go with not taking any action on this.
