### ISSUE TITLE
e621 ripper doesn't support searches containing metatags

### ISSUE THREAD

**Issue by 0ion9** [4pr0n/ripme#299]
An example of a metatag is `date:>2016-01-01` -- a non-tag term that further restricts the search results. It can also be used on its own, usually.

Currently all `/post/index/`  urls containing `:` are rejected by ripme.

**Comment by 4pr0n** [comment]
I didn't write the e621 ripper. It was merged in https://github.com/4pr0n/ripme/pull/265

Paging @kas-luthor ...

**Comment by kas-luthor** [comment]
Yep, I'll need to rewrite URL parsing.
