### ISSUE TITLE
Imgur Albums

### ISSUE THREAD

**Issue by jdam1014** [4pr0n/ripme#300]
Only the first 10 images of a album are downloaded.

**Comment by jhelm9** [comment]
I'm having this issue too. Sometimes it works. Sometimes it only downloads 10.

**Comment by rautamiekka** [comment]
Care to share the links, both functional and non-functional ?

**Comment by jdam1014** [comment]
https://imgur.com/a/nuXbj
There's over 20 photos i the album but ripme will only grab the first ten.

**Comment by Chibdibs** [comment]
you do it in grid view?

**Comment by metaprime** [comment]
See #248
It seems that if you log into an imgur account in non-private browsing and then try to rip, it works. It's a PITB and really hurts the whole point of private browsing and downloading e.g. entire gonewild profiles.

**Comment by metaprime** [comment]
See also #266 and #284

**Comment by Maveee** [comment]
I'm not browsing private, yet I have the same problem. imgdl only downloads the first 10 images!

**Comment by DeiusShrab** [comment]
I've tried logging into an imgur account on multiple browsers in non-private browsing, it hasn't fixed the issue for me

**Comment by Hrxn** [comment]
You can stop trying, it is currently not compatible with Imgur.
They changed something in their API not long ago.

**Comment by 4pr0n** [comment]
Fixed! Give v1.2.10 a spin and see if it works.
