### ISSUE TITLE
Imgur ripper fails to download images via non-direct image links in gonewild profiles.

### ISSUE THREAD

**Issue by metaprime** [4pr0n/ripme#303]
Example: https://www.reddit.com/user/thirstalert/submitted/

Try to rip this and the only thing that gets downloaded is the one submission that was an imgur album.

We could fix this by changing the imgur and gonewild rippers to pre-process those direct link urls to the direct image link, which still seems to work.
## 

**Edit:** I was mistaken (fixed above, more details below). Reddit Enhancement Suite led me to believe the issue was images linked directly, but it appears the issue is actually with images not linked directly.

An example is here:
https://www.reddit.com/user/scottydog00/submitted/
Recent submissions' links look like this: http://i.imgur.com/WXJeAkw.jpg
They all get downloaded.
Older submissions' links look like this: http://imgur.com/PzPT5LC

The recent ones were downloaded fine, but the older ones were missed.

**Comment by 4pr0n** [comment]
Pretty sure this got fixed in 1.2.10. Close the issue if it did.

**Comment by metaprime** [comment]
Seems to be fixed.
