### ISSUE TITLE
not working properly anymore

### ISSUE THREAD

**Issue by kanink007** [4pr0n/ripme#304]
hello
first of all: i love thi script
and it worked fine just some days ago. but now it started fail downdloads. not one or too... thousands.
in my first attempt 10 days ago i sccuessfully downloaded a subreddit with 18.000 pictures. only 20 errors. but thats because these 20 links really didnt work anymore. 
i tried again, same subreddit, and well... maybe 4000 errors? only 1000 downloaded... and thats all. it didnt even find all 18.000 images. it stps now finind all. now it always searches for a different amount of images everytime. i restarted over and over again and luckily had a try where it finally worked again (at least finding all images). after restarting again and again after that, it downloaded most of the images. 
and sometimes, when i restart after closing, it downloads only a single image and finishes.
what could be the problem? did the website change?

**Comment by kanink007** [comment]
okay i think i know my mistake now.. i set "maximum download threads" to 1000. just to be sure: maximum download threads is the limit of the downloaded images each post? reddit is linking them to imgur and most of the albums have more images than 5. isnt it possible to get all images at once each subreddit post?

**Comment by kanink007** [comment]
i think im a bit confused.. could it be that maximum download threas mean the number of simultaneous downloads? lol

**Comment by Hrxn** [comment]
Well, yes, Imgur changed something, so it doesn't work as before.

Yes, maximum download threads means number of simultaneous downloads.

**Comment by version365** [comment]
I don't understand why do you need ripme to download from imgur! imgur itself provides a download option for albums and galleries..

**Comment by lostes** [comment]
That works if you have a small amount of links. Some of us have lists of albums that have automatically been compiled. You can't expect us to click 100+ links. Ripme is excellent solution for this.

**Comment by version365** [comment]
> That works if you have a small amount of links. Some of us have lists of albums that have automatically been compiled. You can't expect us to click 100+ links. Ripme is excellent solution for this.

Well, you have to paste those 100+ links into Ripme too one by one!

**Comment by 4pr0n** [comment]
Fixed in 1.2.9 12eda4080b1ccbf5ea75460869d0cd4608f2b55e
