### ISSUE TITLE
adding eroshare

### ISSUE THREAD

**Issue by kanink007** [4pr0n/ripme#305]
hello
how do i add eroshare (in "pull requests") ? well i have the java source.. how do i make a working jar file? if its possible for.. well not even beginners - never worked with java source files. just need to make a working jar file of the source with ero share

thanks for any help

**Comment by kanink007** [comment]
well now i know how to compile it, but i get an error

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile 
(default-compile) on project ripme: Compilation failure
[ERROR] .../ripme-master/src/main/java/com/rarchives/ripme/utils/RipUtils.java:[85,31] cannot find symbol
[ERROR] symbol:   variable EroShareRipper
[ERROR] location: class com.rarchives.ripme.utils.RipUtils

**Comment by 4pr0n** [comment]
The project uses/requires [Maven](http://maven.apache.org/). The build command (to generate the `.jar` is):

`mvn clean compile assembly:single`

Run that command from the root of the project (where the `src` and `tst` folders are).

The command will create a `ripme-x.x.x-jar-with-dependencies.jar` file in the `target` directory.
