### ISSUE TITLE
changes on imgur causes [!] Unable to rip URL: http://imgur.com/ZZZZZZ

### ISSUE THREAD

**Issue by jadedgnome** [4pr0n/ripme#309]
imgur source use to appear as  <img src="http://i.imgur.com/zzzzzzz.jpg"

now it appears as  <img src="//i.imgur.com/zzzzzzz.jpg"

resulting in errors [!] Unable to rip URL: http://imgur.com/zzzzzzz

**Comment by 4pr0n** [comment]
I think this got fixed... do you have an actual link to the URL to paste into RipMe so I can reproduce?

**Comment by AranciataExcess** [comment]
This is addressed in 1.2.10.

Same issue I reported earlier.

**Comment by 4pr0n** [comment]
So.. is it still an issue?
If it's an issue, Can you provide a link to an imgur album that causes this to happen?
If it's not a problem, please close this issue.

**Comment by AranciataExcess** [comment]
> This is addressed in 1.2.10.
