### ISSUE TITLE
Imgur is downloading only first 10 images on some albums

### ISSUE THREAD

**Issue by SargeRooster** [4pr0n/ripme#312]
I am trying to download a collection of photos and I cant from imgur because it restricts it to the first 10 on only some albums, not all. please help me with this issue.

**Comment by kanink007** [comment]
there https://github.com/4pr0n/ripme/issues/304

**Comment by 4pr0n** [comment]
Fixed in 1.2.9 12eda4080b1ccbf5ea75460869d0cd4608f2b55e
