### ISSUE TITLE
Download a new 3d images site

### ISSUE THREAD

**Issue by MaximIvano** [4pr0n/ripme#322]
Hello,
you are create a greate program .

Can you upgrade your program, added this site support
http://www.cgbytes.com/gallery.aspx ???? To hard copy images one by
one into a personal collection. Please help.﻿
Maybe i need pay for you for that update?

**Comment by MaximIvano** [comment]
mirror url https://www.renderotica.com/gallery.aspx

**Comment by micnorian14** [comment]
Not gonna happen. Premium paid access for most images. Lot of HTML CSS crap to deal with. That said someone likes to post some of the more popular crap from this site on other sites like [this one] (g.e-hentai.org)

**Comment by MaximIvano** [comment]
i can buy premium there and give you access, and you can create for me, please.

**Comment by micnorian14** [comment]
@MaximIvano As cool of you as that would be I have to decline. What little I know about this program is all self taught from existing templates - so a new site would be like me trying to write/read in Chinese. For meow I would suggest something with a more global scope like FoxySpider (addon for Firefox) or messing around with the "DownThemAll" addon. I've had good luck with FoxySpider in the past; unfortunately so did many other people, as a result a lot of the Boorus/imageboards can pretty easily detect and punish you (like BAN your IP and/or login!) so be careful. 

Before you try anything extreme or get desperate I suggest you take a gander at 4chans [Collection Management, Hentai Resources, & General Assistance] (http://boards.4chan.org/h/thread/4405833) and start researching there. I've been there before and IMHO it led me here many moons ago :) [Good luck. We're all counting on you.] (https://www.youtube.com/watch?v=SmHeP9Sve48)
