### ISSUE TITLE
Imgur galleries not recognized

### ISSUE THREAD

**Issue by kayvax** [4pr0n/ripme#328]
Hi,
I stumbled upon some Imgur galleries that are not recognized and can not be downloaded using ripme. Examples:
http://imgur.com/1j8xLmb&y4FZXBa&j4avK7Q&0ET5fRx&u44W2d4
http://imgur.com/NsZBW1V
Also when Imgur link directs to mobile version it is not recognized.

**Comment by i-cant-git** [comment]
`id_1 & id_2 & id_3` combines images, your current bet is to try downloading these separately.

```
http://imgur.com/1j8xLmb
http://imgur.com/y4FZXBa
http://imgur.com/j4avK7Q
http://imgur.com/0ET5fRx
http://imgur.com/u44W2d4
```

Like this.

**Comment by metaprime** [comment]
Looks like there's no action to take here. Closing this issue.
