### ISSUE TITLE
[1.2.13] Subreddit Ripper Doesn't Download

### ISSUE THREAD

**Issue by ghost** [4pr0n/ripme#329]
Instead, RipMe creates the folder and writes a file called "urls.txt" with a list of files. It doesn't actually download any of them, though. In the logs it just prints the same thing over and over again.

C:\RipMe\rips\reddit_sub_asian_midget_porn\urls.txt
Downloaded

**Comment by adamus1red** [comment]
Do you have "Save URLs only" ticked in your configuration settings.

**Comment by metaprime** [comment]
Confirmed this is the behavior when "Save URLs only" is checked. Closing issue.
