### ISSUE TITLE
DeviantART 403, 404, 504 errors

### ISSUE THREAD

**Issue by UnforeseenOcean** [4pr0n/ripme#337]
About 90% of time, dA downloads would result in 403 error and only 2 or 5% of files would be downloaded.
Proof: [http://i.imgur.com/8CpbavT.png](http://i.imgur.com/8CpbavT.png)

**Comment by twisprkl** [comment]
Having this issue as well. I tried to download my own favorite gallery(~~.deviantart.com/favourites) and at least 8 out of 10 downloads result in 403 error.

**Comment by kingharold1st** [comment]
Yes, same here.
i saw, that at first images get downloaded and at some point the 403 error appears and stays.
i tried simply increasing the waiting times in between to downloads but it didn't help.
stopping and starting ripme helps a bit as some of the previous not downloaded images get downloaded but the problem reappears soon.

**Comment by rudolf323** [comment]
Same here, downloaded 2nd page and it started showing 

`Non-retriable status code 403 while downloading`

**Comment by Norithiel** [comment]
Same issue

**Comment by TepigMC** [comment]
I am repeatedly receiving this error. I tried it months ago and came back to it now and it is still not working. The first page works fine, but after that, very few will download.

**Comment by micnorian14** [comment]
DA server appears to detect the program because of the recurring timeout over so much bandwidth. 

After n amount of images DA counts your delay between downloads
If n isn't "human" enough then DA will monitor for specific bandwidth conditions
Contiguous downloads and a strict timed delay = detected bandwidth stealing bot
DA throttles back and you get 403

Suggestion: Add option for "fuzzy" timer. Make adjustable for more stringent sites. 
This will solve the same problem for several sites. Future proofs the app as well.

**Comment by metaprime** [comment]
Copying comments from #325:

---

>@UnforeseenOcean
>
> While downloading from DeviantART, it spews out 504 error on 89% of files it found.
> Here's an example of the error:
> http://www.deviantart.com/download/127366525/indutrial_stock_3_by_bakanekonei.jpg?token=6693e1fa77e9e7aba9e2cd90e0724c07ec729795&ts=1461584723 : Retriable status code 504 while downloading http://www.deviantart.com/download/127366525/indutrial_stock_3_by_bakanekonei.jpg?token=6693e1fa77e9e7aba9e2cd90e0724c07ec729795&ts=1461584723
> 
> I also tried setting the timeout to something like 1,000,000ms but it did little to no effect.
> Plus, the download speed is now crawling. :( 

---

>@utopianduck
>
>Been having similar issues, but with both 504 and 404 errors. Changing timeout speed having no real effect either

**Comment by micnorian14** [comment]
As I stated before, the error you can see in your log has to do with DA issuing tokens to clients for downloading full size images. If you open ripme, let it start downloading as usual;
Wait and watch for 403 errors to begin
Pause it for a few seconds
In this time change the delay to something different ie from 9999ms to 8888ms
No more than 9,999ms as I think 5 digits is out of range (10,000ms is 10 seconds bro)
Resume
Rinse and repeat. 

This more closely simulates real web surfing traffic than a bot requesting sequential files. This is effectively a fuzzy timer. This works for me. I've moved on to bigger things in life but I thought I'd come back here and share what vague understanding of what little coding I know. And knowing is half the battle!

**Comment by rautamiekka** [comment]
This problem hasn't existed for a long time if successfully ripping dozens of galleries and folders is to be believed. Current version is 1.5.7.
