### ISSUE TITLE
[Basic Feature Request] Specify list of URLs as input

### ISSUE THREAD

**Issue by reallyuniquename** [4pr0n/ripme#343]
It would be really usefull to have the ability to specify list of input URLs as TXT file.

**Comment by JoshKastang** [comment]
You can write a quick shell script to accomplish this already. 

Assuming you're on Linux you can do something like: 

`while read url; do
    java -jar ripme.jar -u "$url"
done <urls.txt`

**Comment by reallyuniquename** [comment]
Great workaround but I'd prefer to have this as native feature so app could report failed urls, could be paused etc. Spawning new process for every url is not neat solution.

**Comment by autoborg** [comment]
More automation, I like it! Unfortunately, 4pr0n seems to be AWOL, so we might not it implemented for a while.

**Comment by JoshKastang** [comment]
Implemented this - PR #344 adds the -f flag to the CLI and will take in a list of URLs. 

Very minimally tested, let me know if there are any issues.

**Comment by metaprime** [comment]
Merged in #334 so I'm closing this issue.
