### ISSUE TITLE
8muses ripper doesn't work since site update

### ISSUE THREAD

**Issue by Korons** [4pr0n/ripme#345]
8muses.com got updated recently and the ripper doesn't work on the new version of the site

**Comment by kay9** [comment]
Yup. Pls update the script.

**Comment by rephormat** [comment]
@Korons @kay9 Could you please provide the version of ripme you are using, an example URL to rip, and describe exactly what you're seeing?

**Comment by Korons** [comment]
@rephormat The latest update to ripme (1.3.0) has fixed the issue
