### ISSUE TITLE
xHamster: can no longer rip picture galleries

### ISSUE THREAD

**Issue by Costanegra** [4pr0n/ripme#360]
I can no longer download picture galleries from xHamster. I can, however, download GIF galleries. 

Thanks.

**Comment by metaprime** [comment]
@slauzon if you've got a fix for this could you submit a PR to this repo so I can merge it in? Thanks!

**Comment by metaprime** [comment]
Tried with this link: https://xhamster.com/photos/gallery/7254664/japanese_dolls_4_asahi_mizuno.html - it seemed to detect links but was unable to download. I'll try ripping the album with your fix.

**Comment by metaprime** [comment]
Works. I'm merging in your fix.

**Comment by metaprime** [comment]
Whoops.

**Comment by jimbotomato** [comment]
XHamster changed their gallery URL format so Ripme doesn't detect it anymore.

Previously:
xha*****.com/photos/gallery/@@numbers@@/@@name@@.html

Now:
xha******.com/photos/gallery/@@name@@-@@numbers@@

**Comment by raviteja1992y** [comment]
Hi, I am trying to fix this

**Comment by metaprime** [comment]
@raviteja1992y How's it going?
