### ISSUE TITLE
Imgur: when ripping user, include album names in subdirectories instead of just GIDs

### ISSUE THREAD

**Issue by Verifirs** [4pr0n/ripme#365]
Add album names for albums ripped from [username].imgur.com

Shouldn't be too difficult - imgdl has this functionality (Although I have found it is less stable).

**Comment by metaprime** [comment]
Yep, this is definitely something I've been wanting as well.

**Comment by metaprime** [comment]
Why not add users into the mix if available?

https://imgur.com/a/qjjaF (user: `a .post-account`)

https://imgur.com/a/9Egbz (includes username) (title: `h1 .post-title`)

Ensure that getting album titles works for ripping all albums from a user's page (e.g. https://poiuytrewq001.imgur.com/ or for something with a bit less content: https://emspace.imgur.com/)

**Comment by metaprime** [comment]
Holding off on the usernames for now. I feel like that's irrelevant information for most people, so it should be opt-in only with a configuration option to turn it on. For most people, I'd suspect the user who created the album is not important, unless they are ripping the whole user's profile.

**Comment by metaprime** [comment]
Duplicate of #94
