### ISSUE TITLE
[META] New Collaborator in Town!

### ISSUE THREAD

**Issue by metaprime** [4pr0n/ripme#369]
Hi all, thanks to @4pr0n for adding me as a collaborator on this project. Looks like I'll be taking over maintenance, and there's no need to use a fork to take over the project anymore. That saves everyone some trouble. I'm not sure yet about how to deploy new updates but I'll get that figured out.

Bring on the pull requests!

**Comment by Hrxn** [comment]
Thank you!

That's really good news 😄

**Comment by metaprime** [comment]
@JoshKastang @sleaze @gabozo - I'm tagging you because of your work over at https://github.com/4pr0n/ripme/pull/336. It looks like the development of this project has diverged into several forks. I'd like to reunify the development effort. I'd appreciate any help you could give as far as sorting out the various patches flying around. I'm happy to merge anything which fixes broken functionality.

Fixing up existing (but broken) functionality is going to be my primary focus for the time being, until we get everything back to stable. I'll leave requests for new features alone for the moment.

**Comment by metaprime** [comment]
I created a Gitter room so we have a venue for chatting about the project besides issues and pull requests. Might be helpful. https://gitter.im/4pr0n-ripme/

**Comment by metaprime** [comment]
Cleaning up issues: defer to latest META issue #400
