### ISSUE TITLE
Add button to open chosen rips save directory.

### ISSUE THREAD

**Issue by metaprime** [4pr0n/ripme#372]
![image](https://cloud.githubusercontent.com/assets/7526632/21313107/a6ed7bc0-c5a4-11e6-9af2-c4a6cd2af8bf.png)

Change the "Select Save Directory..." button to two buttons: "Choose Directory..." "Open"

Sometimes when a rip fails or is interrupted, you can't easily open the rips directory. This is annoying when you've queued up a lot of rips and the last one fails, but you still want to see all of the successful ones.

**Comment by rephormat** [comment]
What about if we make the label look like a hyperlink so users would know it's clickable and then open the directory that way?  If this is acceptable I've already written up the code to do it.

**Comment by metaprime** [comment]
@rephormat Sounds fair. Also avoids having to rename labels and mess with the layou. I'm definitely willing to give that a try. I look forward to your pull request!
