### ISSUE TITLE
Twitter: not ripping Videos

### ISSUE THREAD

**Issue by tehloxely** [4pr0n/ripme#381]
I was trying to rip a Twitter account that has ~290 photos and vidoes, but RipMe only downloaded 190.

**Comment by metaprime** [comment]
@tehloxely please provide a link to the Twitter account so I can test with it and figure out what's going on.

**Comment by tehloxely** [comment]
https://twitter.com/littlekeish

**Comment by tehloxely** [comment]
Here's what it looks like in v1.3.0.

![untitled-1](https://cloud.githubusercontent.com/assets/1208778/21391114/35cf5f52-c758-11e6-8c30-d20f124c9a05.png)

**Comment by metaprime** [comment]
@tehloxely Thanks for confirming it's still an issue. By the way, how did you determine that it contains ~290 images and videos?

It looks like jpgs are getting ripped just fine, but videos are not.

**Comment by IT6uru** [comment]
If more than one picture is in a post, only the first one will download. This has been happening for a while.

**Comment by metaprime** [comment]
@IT6uru thanks for clarifying that happens as well. I think that issue is already open in #182 but I think the video content issue is another issue.

**Comment by tehloxely** [comment]
Now that you mention it. I do not have any videos downloaded. Just the images have downloaded.
Here's how I can see how many media files are on her Twitter.
![untitled](https://cloud.githubusercontent.com/assets/1208778/21392975/65d062c0-c760-11e6-8753-fcf19f757fda.png)

**Comment by metaprime** [comment]
@tehloxely huh, yeah I thought twitter had a display like that. For some reason it wasn't showing up for me. Maybe I need to log in first?

**Comment by tehloxely** [comment]
Either you have to log in or have any adblocking disabled. I cannot remember which :P

**Comment by metaprime** [comment]
Might be both....

**Comment by metaprime** [comment]
I changed the title of this issue to focus on the Video issue mainly. I think between this and the missing multiple images (#182) we should cover most or all of the Twitter issues.

**Comment by metaprime** [comment]
Fixed in #478
