### ISSUE TITLE
Tumblr Rip Error

### ISSUE THREAD

**Issue by tehloxely** [4pr0n/ripme#385]
When I add this link from Tumblr
http://rapepuppy.tumblr.com/tagged/me

It gives me this error
Downloading http://api.tumblr.com/v2/blog/rapepuppy.tumblr.com/posts/photo?api_key=v5kUqGQXUtmF7K0itri1DGtgTs0VQpbSEbh1jxYgj9d2Sq18F8&offset=0&tag=me
Rip complete, saved to G:\Images\Rips\tumblr_rapepuppy.tumblr.com_tag_me
Failed to load http://api.tumblr.com/v2/blog/rapepuppy.tumblr.com/posts/photo?api_key=v5kUqGQXUtmF7K0itri1DGtgTs0VQpbSEbh1jxYgj9d2Sq18F8&offset=0&tag=me after 1 attempts

**Comment by metaprime** [comment]
@tehloxely which version of ripme are you using? Have you tried updating to [1.3.0](https://github.com/4pr0n/ripme/releases/tag/1.3.0). This should be fixed (you'll see a new API key in the log (besides `v5kUqGQXUtmF7K0itri1DGtgTs0VQpbSEbh1jxYgj9d2Sq18F8`)

**Comment by tehloxely** [comment]
I didn't see there was an update. I tried hitting Update on the version that I have v1.2.13. It worked on the new version. Thank you.

**Comment by metaprime** [comment]
@tehloxely Yeah, I'm working with @4pr0n to get the website updated with a version that will know to look on GitHub for updates in the future. Until that happens, it's unfortunate, but the only people who get updated will be the ones that come to GitHub and notice there's an update available.
