### ISSUE TITLE
When closing the window, sometimes javaw.exe keeps running

### ISSUE THREAD

**Issue by metaprime** [4pr0n/ripme#412]
I've noticed this since I started working on the project but I'm fairly sure it's not because of anything I changed.

I've also noticed this sometimes with 1.2.x so it might not be a new problem. Definitely need to look into this.

---

For what it's worth I've just tried a few things with 1.4.1:

* Launched by double-clicking and closed repeatedly, with no leftover processes.
* Launched by `java -jar ripme.jar` and closed repeatedly, with no leftover processes.
* Launched by `javaw -jar ripme.jar` and closed repeatedly, with no leftover processes.

I've also used the app to do some rips, and closed it after a session, multiple times over the past few days, and have seen no leftover processes.

So based on those, no repro for me. I'll keep an eye out, but without a consistent repro it's going to be difficult to track down and fix and issue, or even to know whether the issue is fixed.

**Comment by metaprime** [comment]
For what it's worth I've just tried a few things with 1.4.1:

* Launched by double-clicking and closed repeatedly, with no leftover processes.
* Launched by `java -jar ripme.jar` and closed repeatedly, with no leftover processes.
* Launched by `javaw -jar ripme.jar` and closed repeatedly, with no leftover processes.

I've also used the app to do some rips, and closed it after a session, multiple times over the past few days, and have seen no leftover processes.

So based on those, no repro for me. I'll keep an eye out, but without a consistent repro it's going to be difficult to track down and fix and issue, or even to know whether the issue is fixed.

**Comment by metaprime** [comment]
I'm having a hard time reproing this issue (haven't seen it myself in a while).

If you have specific steps that consistently repro this issue, please share. Thanks :)

**Comment by rautamiekka** [comment]
It doesn't happen with just RipMe, it seems to be a generic Java problem cuz it has happened with anything coded in Java in my experience.

**Comment by metaprime** [comment]
@rautamiekka That's been my experience as well.

**Comment by i-cant-git** [comment]
I can confirm, when you click close/X button, it says in background.

Windows 8 64-bit, RipMe 1.4.1, Java 8 Update 111

**Comment by metaprime** [comment]
It has happened to me a few times, so yes I've seen it happen, but it's not reproducible enough to study, and from what I can tell, there's nothing in the code that could cause this, but rather it seems to be an issue upstream in the implementation of javaw.exe / the JVM.

I wonder if it repros running under Java 6 or Java 7, or only Java 8.

**Comment by rautamiekka** [comment]
First, try updating your Java. Unless you're pressed with disk space, get the JDK instead of JRE and install both when you're asked in custom mode, optionally leaving the source code out. Before you install a newer one, uninstall all of the previous ones you know you don't have to keep.

**Comment by revanwolf** [comment]
I also have this problem but only when the "restore window position" is checked, it close normally if it's unchecked.

**Comment by metaprime** [comment]
@revanwolf That sounds like a coincidence. That option only affects the window positioning on start-up.

**Comment by rautamiekka** [comment]
^ Umm, I think it's not a coincidence: I edited the config to disable window location recalling and javaw.exe never stayed in the background of the around a dozen attempts, but of all the 4 attempts with the recalling on it stayed in the background, needing to be killed through Task Manager. Now, it's weird, but this problem have occurred to me way less often than when trying now. This whole problem of javaw staying in the background makes no sense in RipMe's case as far as I've read the source code, but it happens.

Much earlier when I tried to look into this crash thingy I used VisualVM, but tbh I never made any sense outta it.

**Comment by Ennapocryph** [comment]
Can confirm what @revanwolf said, it doesn't happen anymore when I uncheck the "Restore window position" option.

**Comment by metaprime** [comment]
Well... that's certainly a disturbing development. I'll consider this a workaround but I don't want to close this issue yet.

An obvious thing to do to fix this problem then is to completely disable the window position restore option, but I'm not sure I really want to do that...

**Comment by metaprime** [comment]
Closed along with https://github.com/RipMeApp/ripme/issues/70
