### ISSUE TITLE
Queued pulls not persisting on close of program

### ISSUE THREAD

**Issue by notacompletemoron** [4pr0n/ripme#413]
I think the title is pretty self-explanatory.

I just dropped in the 1.4.1 jar on top of the existing 1.3.0 jar. I did nothing else. I retained the existing history and rip properties files.

**Comment by metaprime** [comment]
I believe this is a known issue and would be the case whether you had updated or not, if you closed the app without letting the queue finish.

I think it's just that it was never supported to keep the queue past a restart. I could be wrong about that. If it was previously supported, I don't know when this functionality broke.

**Comment by metaprime** [comment]
Duplicate of #175

**Comment by notacompletemoron** [comment]
It did work with 1.2.8 (I think that was the last version I had before 1.3.0).

**Comment by metaprime** [comment]
Ok I'll look into it. Wouldn't want to repeat work in case it's only a little broken. But that feature might need to be written from scratch.
