### ISSUE TITLE
8muses directory naming is poorly chosen

### ISSUE THREAD

**Issue by lembarek** [4pr0n/ripme#429]
when I try to download from 8muses this:
https://www.8muses.com/comix/album/jab-comics/johnny-testicles/issue-1
https://www.8muses.com/comix/album/jab-comics/the-creepies/issue-1
both go to the same folder:
8muses_Issue_1_online_for_free_at_8muses.com
could you fix that, please.

**Comment by cyian-1756** [comment]
I've run into the same issue, it should be pretty simple to fix. All that has to be to done is split the url and add each item after album to the folder name.

So 8muses_Issue_1_online_for_free_at_8muses.com becomes 8muses_jab-comics_the-creepies_issue-1

**Comment by cyian-1756** [comment]
`// Attempt to use album title as GID
            Element titleElement = getFirstPage().select("meta[name=description]").first();
            String title = titleElement.attr("content");
            title = title.substring(title.lastIndexOf('/') + 1);
            return getHost() + "_" + title.trim();`

That's the code which is causing the naming issue by changing it to

`// Attempt to use album title as GID
            Element titleElement = getFirstPage().select("meta[name=description]").first();
            String title = titleElement.attr("content");
            title = title.replace("A huge collection of free porn comics for adults. Read", "");
            title = title.replace("online for free at 8muses.com", "");
            return getHost() + "_" + title.trim();`

The name of https://www.8muses.com/comix/album/jab-comics/the-creepies/issue-1 becomes 8muses_The_Creepies_Issue_1

Give me a while to test it and I'll make a pull request later on today

**Comment by metaprime** [comment]
Fixed by #451
