### ISSUE TITLE
4 chan not ripping

### ISSUE THREAD

**Issue by icaruss22** [4pr0n/ripme#432]
I keep getting this error when I try to rip a thread

No images found at http://boards.4chan.org/b/thread/XXXXXXXX

**Comment by cyian-1756** [comment]
Can you give me a link to the thread you're trying to rip?

**Comment by icaruss22** [comment]
it does it with all 

try this one http://boards.4chan.org/b/thread/719969998

**Comment by icaruss22** [comment]
![capture](https://cloud.githubusercontent.com/assets/25265418/22201592/34e37490-e132-11e6-9bda-9f66b88bd141.PNG)

**Comment by cyian-1756** [comment]
Found the bug! 4chan added a new subdomain (is2.4chan.org). I'll commit the fix to my fork and it should be in the main branch around mid feb 

If you want it before then just download and build my [fork](https://github.com/cyian-1756/ripme)

**Comment by MrSoloRojo** [comment]
"If you want it before then just download and build my fork"

How do I do this? Complete noob to Maven.

**Comment by cyian-1756** [comment]
@MrSoloRojo 

way one
1) install git

2) install maven

3) enter `git clone https://github.com/cyian-1756/ripme.git` into the command line

4) enter my fork with `cd ripme` 

5) enter `mvn clean compile assembly:single`

Way two

1) Download this zip file https://github.com/cyian-1756/ripme/archive/master.zip

2) unzip it

3) Install maven

4) Open the unzipped folder in the commandline (cd /where/ever/you/unzipped/the/folder)

5) Run `mvn clean compile assembly:single` from the commandline

**Comment by cyian-1756** [comment]
@MrSoloRojo Did you ever get it working?

**Comment by Hrxn** [comment]
NB: You need to have an JDK installed for Maven to work, if I recall it correctly..

**Comment by MrSoloRojo** [comment]
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (C:\Users\MyUserName). Please verify you invoked Maven from the correct directory. -> [Help 1]

I guess I pathed something wrong, even though mvn -v gives me a version number.

**Comment by cyian-1756** [comment]
@MrSoloRojo 

> I guess I pathed something wrong

Lol yup, the path should be where you downloaded and extracted the zip. For example if you extracted it in Downloads the path would look something like `c:\users\yourusername\downloads\ripme

**Comment by cyian-1756** [comment]
@MrSoloRojo 

https://github.com/cyian-1756/ripme/releases/download/1.4.1/ripme-1.4.1-jar-with-dependencies.jar

That's a link to a precompiled version of my fork you should be able to just download and run it

**Comment by metaprime** [comment]
@cyian-1756 Aren't build instructions somewhere on this repo or wiki? I don't have time to go looking. If not, I'll add your instructions somewhere.

**Comment by cyian-1756** [comment]
@metaprime 

> Aren't build instructions somewhere on this repo or wiki?

Yup. There's also a build.bat file (Which should be included in the "how to build" for windows)

**Comment by metaprime** [comment]
Fixed by #452.
