### ISSUE TITLE
Should sites with shared code bases each get their own ripper?

### ISSUE THREAD

**Issue by cyian-1756** [4pr0n/ripme#434]
I'm writing rippers and I've found a few sites (Mostly wordpress comic sites) that could rolled into one ripper and I'm wondering if that should be done

It would create less code to maintain (change one ripper instead of several) but if a site changed it's wordpress theme it would break the ripper (And the site would then require it's own ripper)

**Comment by metaprime** [comment]
Discussion here #361 might be relevant. I agree that unnecessary duplication sucks but we should make sure we go about it the right way. Sites changing their themes is already a problem. If it looks like we could roll a bunch of sites into a "WordpressRipper" or similar, we could try that. This would be something like how the ChanRipper specifies multiple domains on which the logic applies.

**Comment by metaprime** [comment]
@cyian-1756 Since the wordpress comic ripper is now live, I'd like to close this issue. I approve of refactoring in any way which makes things more easily maintainable, but I think we can track each item as a separate issue.
