### ISSUE TITLE
e-hentai no longer working (changed URL)

### ISSUE THREAD

**Issue by zakalwe0514** [4pr0n/ripme#436]
e-hentai has dropped the leading g from their gallery urls. Used to be g.e-hentai.org, now it's just e-hentai.org, but that's causing RipMe to not recognize the gallery and invoke the correct ripper. 

No other changes that I can tell, although it would be cool if, while someone was in the code, if they could teach it to grab the high res file where it exists.

**Comment by zakalwe0514** [comment]
actually, I missed something else. It's now using https instead of http. Don't know if that makes a difference or not.

**Comment by cyian-1756** [comment]
@zakalwe0514 Can you provide a example album?

**Comment by cyian-1756** [comment]
Fixed in my fork, the fix should be in main around feb

**Comment by zakalwe0514** [comment]
Here's a sample album:
https://e-hentai.org/g/1022686/9d910dfe81/

Image 48 in that album (https://e-hentai.org/s/83be9ff73b/1022686-48) has a hi-res version (found at the bottom of the page as a hyperlink, not as the embedded image).

**Comment by cyian-1756** [comment]
@zakalwe0514 thanks for the example album, I've changed up the e-hentai ripper and a fixed version of ripme should be out in a few weeks

**Comment by metaprime** [comment]
@cyian-1756 Thanks for the fix in your PR. :) I'll try to get these fixes merged in ASAP (first I need to catch up on work now that I'm back from vacation).

**Comment by zakalwe0514** [comment]
Thanks folks! That's great news. Look forward to seeing the new version.

**Comment by metaprime** [comment]
Fixed in #453
