### ISSUE TITLE
tumblr rip error

### ISSUE THREAD

**Issue by droidberg** [4pr0n/ripme#438]
so i have been trying to rip various tumblr pages and non seem to work. i keep getting the same error:

Downloading http://api.tumblr.com/v2/blog/amazonreviewlols.tumblr.com/posts/photo?api_key=JFNLu3CbINQjRdUvZibXW9VpSEVYYtiPJ86o8YmvgLZIoKyuNX&offset=0
Rip complete, saved to J:\[tumblr rips]\tumblr_amazonreviewlols.tumblr.com
null

the site i tried is:

http://amazonreviewlols.tumblr.com/

**Comment by cyian-1756** [comment]
I was getting the same error earlier, I'd image it's because of the default api key. Make a tumblr account, get an api and use it to replace the default one and it should work fine

**Comment by droidberg** [comment]
@ cyian-1756  
oh snap!! thanks for the help! this worked and now i can go back to enjoying my funny pics. i appreciate it!

**Comment by cyian-1756** [comment]
@droidberg No problem, but could you close the issue please?

**Comment by droidberg** [comment]
@ cyian-1756
SORRY!! closed!
