### ISSUE TITLE
Smutty.com looks like they changed their image code. Getting Error: No Protocol

### ISSUE THREAD

**Issue by Kimberlie03** [4pr0n/ripme#442]
Pretty much as the title says. Looks like the links now start with "//" which is confusing the ripper.

**Comment by cyian-1756** [comment]
Can you post an example album?

**Comment by Kimberlie03** [comment]
Yup, sorry for the tardiness on this.

https://smutty.com/h/petite/

**Comment by metaprime** [comment]
Fixed in https://github.com/RipMeApp/ripme/commit/1214d191874f4bcee87ca7a54b2560349cc23e0a
