### ISSUE TITLE
Tumblr no longer working

### ISSUE THREAD

**Issue by GenericUsername96** [4pr0n/ripme#449]
Hey guys, don't know if it's just a client based issue or the ripper itself but for the past month I haven't been able to get Ripme to work with Tumblr

Downloading http://api.tumblr.com/v2/blog/yepjeeway.tumblr.com/posts/photo?api_key=v5kUqGQXUtmF7K0itri1DGtgTs0VQpbSEbh1jxYgj9d2Sq18F8&offset=0

Failed to load http://api.tumblr.com/v2/blog/yepjeeway.tumblr.com/posts/photo?api_key=v5kUqGQXUtmF7K0itri1DGtgTs0VQpbSEbh1jxYgj9d2Sq18F8&offset=0 after 5 attempts

**Comment by Hrxn** [comment]
#416
