### ISSUE TITLE
Logger unable to locate config files based on directory path

### ISSUE THREAD

**Issue by Calvin-Ho** [4pr0n/ripme#450]
Not sure what exactly is causing this error, but I'm guessing that it has to do with the handling of special characters with regards to filepaths.

I'm seeing this error on 1.4.1.

You can see the output [here](http://imgur.com/EJweosw) and I also put it [here](http://pastebin.com/hA7uKW77) in text form.

When I move the jar to the root of my D:\ drive, it runs no problem.

Running on Windows 8.1 x64 with Java 1.8.0_111.

**Comment by rautamiekka** [comment]
First, try updating your Java. Unless you're pressed with disk space, get the JDK instead of JRE and install both when you're asked in custom mode, optionally leaving the source code out. Before you install a newer one, uninstall all of the previous ones you know you don't have to keep.

**Comment by Calvin-Ho** [comment]
Same problem after updating.  Now running Java 1.8.0_121.

**Comment by midweekmayhem** [comment]
Java interprets "!" (exclamation character) in your file path as end of jar archive file name, and this prevents ripme to read log4.properties.

I don't think we can fix this as this is part of java/jar spec. Try renaming your folder name from "Fun Time!" to "Fun Time" or start ripme in D:\ drive.

**Comment by Calvin-Ho** [comment]
Alright, it's not really a big problem to me.  I'll just move the jar to another drive.

Thanks for the responses.  I'll close the issue.
