### ISSUE TITLE
Tumblr reporing NULL

### ISSUE THREAD

**Issue by tehloxely** [4pr0n/ripme#458]
I tried to rip http://purerebelmodel.tumblr.com/tagged/me and the RipMe log is this:

> Downloading http://api.tumblr.com/v2/blog/purerebelmodel.tumblr.com/posts/photo?api_key=JFNLu3CbINQjRdUvZibXW9VpSEVYYtiPJ86o8YmvgLZIoKyuNX&offset=0&tag=me
Rip complete, saved to G:\Images\Rips\tumblr_purerebelmodel.tumblr.com_tag_me
null

**Comment by cyian-1756** [comment]
It's because the ripme api key has been rate limited. Change out the `tumblr.auth` key in rip.properties with your own newly generated key and you'll be able to rip tumblr with no issue

To generate a new key you need to [register an application](https://www.tumblr.com/oauth/apps)
