### ISSUE TITLE
Eroshare album titles

### ISSUE THREAD

**Issue by metaprime** [4pr0n/ripme#460]
Get title from album page for the folder name.

**Comment by cyian-1756** [comment]
Can you post a link to an example album?

**Comment by metaprime** [comment]
Can't remember where I saw one. Pulling a few posts from https://www.reddit.com/search?q=eroshare+album&sort=relevance&t=all

Album with title, username, and 2 videos:
https://eroshare.com/dz8rx7mt

Here's an album with no title, but username:
https://eroshare.com/63uw1r2x

**Comment by cyian-1756** [comment]
@metaprime 

I added title grabbing in [this](https://github.com/4pr0n/ripme/pull/486) PR
