### ISSUE TITLE
eroshare: not able to rip eroshare user pages

### ISSUE THREAD

**Issue by acureon** [4pr0n/ripme#465]
I know ripme has support for eroshare through reddit but if I just put in the URL of an eroshare user page it won't rip all of their uploaded content and instead says no ablum found or something. 

Example: https://eroshare.com/u/onlybestones

**Comment by metaprime** [comment]
Yes, interestingly, ripping direct links to content is already supported, but not user pages. I'm guessing it was an oversight.

**Comment by acureon** [comment]
Thank you sir!

**Comment by acureon** [comment]
Hi there! Just wondering what the status of this is, as eroshare will be shutting down soon >.<

**Comment by cyian-1756** [comment]
@acureon No ones worked on it yet, I;m going to take a crack at and see if I can get profile ripping done before the site shuts down

**Comment by cyian-1756** [comment]
@acureon  I have basic profile ripping working (It only rips the first page so far) I should have it completely done by tomorrow

**Comment by acureon** [comment]
@cyian-1756 wow thank you so much!! You're amazing! I really appreciate your work :)

**Comment by cyian-1756** [comment]
@acureon I have profile ripping working and made a [PR](https://github.com/4pr0n/ripme/pull/578), but I have no idea when it will be merged into master

**Comment by metaprime** [comment]
I'll merge and release that PR first thing tomorrow morning. It's important that we can rip that site before it goes down for good. 

Fwiw there's an archival effort underway which might even allow us to redirect links to archive.org or similar to download content. More on that later.

**Comment by metaprime** [comment]
@cyian-1756 This doesn't seem to work with the rip URLs only option enabled but that wasn't worth blocking the merge.

**Comment by metaprime** [comment]
Released in 1.4.20: https://github.com/4pr0n/ripme/releases/tag/1.4.20
