### ISSUE TITLE
Hentai Foundry and Fur Affinity

### ISSUE THREAD

**Issue by sbobbo** [4pr0n/ripme#479]
Can support for http://www.hentai-foundry.com and https://www.furaffinity.net/ be fixed? Artist and favorites galleries fail for me on both sites.

**Comment by cyian-1756** [comment]
Can you post the error messages (if any)?

**Comment by sbobbo** [comment]
`http://pictures.hentai-foundry.com//m/Moonbound/490354.jpg : Non-retriable status code 404 while downloading http://pictures.hentai-foundry.com//m/Moonbound/490354.jpg
Downloading http://pictures.hentai-foundry.com//m/Moonbound/486743.jpg
http://pictures.hentai-foundry.com//m/Moonbound/493495.jpg : Non-retriable status code 404 while downloading http://pictures.hentai-foundry.com//m/Moonbound/493495.jpg
Downloading http://pictures.hentai-foundry.com//m/Moonbound/485082.jpg
http://pictures.hentai-foundry.com//m/Moonbound/487289.jpg : Non-retriable status code 404 while downloading http://pictures.hentai-foundry.com//m/Moonbound/487289.jpg
Downloading http://pictures.hentai-foundry.com//m/Moonbound/482527.jpg
http://pictures.hentai-foundry.com//m/Moonbound/488017.jpg : Non-retriable status code 404 while downloading http://pictures.hentai-foundry.com//m/Moonbound/488017.jpg
Downloading http://pictures.hentai-foundry.com//m/Moonbound/481268.jpg
Downloading next page
http://pictures.hentai-foundry.com//m/Moonbound/491928.jpg : Non-retriable status code 404 while downloading http://pictures.hentai-foundry.com//m/Moonbound/491928.jpg
Downloading http://pictures.hentai-foundry.com//m/Moonbound/479962.jpg
Downloading next page
http://pictures.hentai-foundry.com//m/Moonbound/486743.jpg : Non-retriable status code 404 while downloading http://pictures.hentai-foundry.com//m/Moonbound/486743.jpg
Downloading http://pictures.hentai-foundry.com//m/Moonbound/477824.jpg
http://pictures.hentai-foundry.com//m/Moonbound/485082.jpg : Non-retriable status code 404 while downloading http://pictures.hentai-foundry.com//m/Moonbound/485082.jpg
Downloading http://pictures.hentai-foundry.com//m/Moonbound/472806.jpg
http://pictures.hentai-foundry.com//m/Moonbound/482527.jpg : Non-retriable status code 404 while downloading http://pictures.hentai-foundry.com//m/Moonbound/482527.jpg
Downloading http://pictures.hentai-foundry.com//m/Moonbound/473364.jpg
http://pictures.hentai-foundry.com//m/Moonbound/481268.jpg : Non-retriable status code 404 while downloading http://pictures.hentai-foundry.com//m/Moonbound/481268.jpg
Downloading http://pictures.hentai-foundry.com//m/Moonbound/471949.jpg
http://pictures.hentai-foundry.com//m/Moonbound/479962.jpg : Non-retriable status code 404 while downloading http://pictures.hentai-foundry.com//m/Moonbound/479962.jpg
Downloading http://pictures.hentai-foundry.com//m/Moonbound/470707.jpg
http://pictures.hentai-foundry.com//m/Moonbound/477824.jpg : Non-retriable status code 404 while downloading http://pictures.hentai-foundry.com//m/Moonbound/477824.jpg
Downloading http://pictures.hentai-foundry.com//m/Moonbound/470326.jpg`

The Non-retriable line is in red.

FA:
'Downloading https://www.furaffinity.net/gallery/miles-df/
Rip complete, saved to D:\Downloads\Online\RipMe\rips\furaffinity_miles-df
No images found at https://www.furaffinity.net/gallery/miles-df/'

**Comment by cyian-1756** [comment]
Can you post the HF url you're trying to rip?

**Comment by sbobbo** [comment]
http://www.hentai-foundry.com/pictures/user/Moonbound

**Comment by cyian-1756** [comment]
I've fixed FA (There was a minor css change to the site). My pull should be merged into master in the next few weeks

**Comment by sbobbo** [comment]
Awesome, thanks!

**Comment by cyian-1756** [comment]
I've also fix HF (They changed their file name format). Like my other PR it should be in master in the next few weeks

Also for the future, each site should get it's own issue

**Comment by sbobbo** [comment]
Ah, sorry about that. Will do that next time. Thanks again!

**Comment by cyian-1756** [comment]
@sbobbo No need to close the issue until the PRs have been merged
