### ISSUE TITLE
The wiki should be updated and allow editing

### ISSUE THREAD

**Issue by cyian-1756** [4pr0n/ripme#485]
The wiki is missing a ton of info/examples (even for simple things like canRip())

The wiki also appears to be locked to only certain users meaning that atm no one can update it

**Comment by metaprime** [comment]
Yeah, I'm not an admin on the repo so I can't give anyone else edit permissions, but I myself do have edit permissions. I think I'll go ahead and make a repo for the wiki so people can make PRs against the code itself, and then I'll merge and push to the wiki's repo.

In the meantime I'll ping 4_pr0n on reddit and see if there's a better option here.

**Comment by metaprime** [comment]
Added https://github.com/RipMeApp/ripme-wiki for PRs on the Wiki

**Comment by metaprime** [comment]
@cyian-1756 does this work for you?

**Comment by cyian-1756** [comment]
@metaprime yup.
