### ISSUE TITLE
How can I get the latest ripme features?

### ISSUE THREAD

**Issue by L3sb0t** [4pr0n/ripme#488]
I don't know anything about code and have no clue how to use the new ripper. Can someone walk me through it?

**Comment by metaprime** [comment]
Download the latest release from https://github.com/4pr0n/ripme/releases and have fun!

**Comment by L3sb0t** [comment]
How do I run the program? I don't see an exe. file or anything I know how to use.

**Comment by cyian-1756** [comment]
You need to have java installed. You can then run the .jar as if it were a exe

**Comment by L3sb0t** [comment]
Am I supposed to make the jar. file? I don't see a jar. file in the zip.

**Comment by cyian-1756** [comment]
https://github.com/4pr0n/ripme/releases/download/1.4.6/ripme.jar

That's the file you want

**Comment by L3sb0t** [comment]
Thanks, I got it to work. Before, for whatever reason, java didn't recognize the file I had but it did after I reset my pc.
