### ISSUE TITLE
Tumblr rips report null

### ISSUE THREAD

**Issue by L3sb0t** [4pr0n/ripme#490]
When I try to rip from Tumblr, I get a red message saying "null".

**Comment by cyian-1756** [comment]
What url are you trying to rip and what version of ripme are you running?

**Comment by L3sb0t** [comment]
The url is http://beeple.tumblr.com/ and I'm running the most recent ripper, 1.4.6 .

**Comment by cyian-1756** [comment]
It's a too many requests error, you have to replace the tumblr api key (`tumblr.auth` in rip.properties) with your own tumblr api key.

You'll need to [register an application](https://www.tumblr.com/oauth/apps) to get an api key.

**Comment by cyian-1756** [comment]
@L3sb0t Did replacing the api key solve this issue? If so can you please close this issue

**Comment by amolad** [comment]
>You'll need to register an application to get an api key.

HOW do you do that?

**Comment by cyian-1756** [comment]
@amolad 

You need a Tumblr account

Go here: https://api.tumblr.com/console

Click Register a new application

Fill out all required fields, etc. Just enter something

**Comment by amolad** [comment]
>You need a Tumblr account

>Go here: https://api.tumblr.com/console

>Click Register a new application

>Fill out all required fields, etc. Just enter something

I don't want a fucking tumblr account. 
Just forget it. JDownloader rips tumblr pages quite easily.

**Comment by metaprime** [comment]
You just get a key and leave it. I'm not sure what the problem is here.

Someone want to look into how JDownloader manages to get around rate limiting without needing a key?

**Comment by Hrxn** [comment]
Someone know an open source repo of JDownloader?

Not sure if that is really possible in Tumblr's case, though. You use the API, you need a key.
Perhaps they're doing it the "good" old way, retrieving HTML and then scraping it?

**Comment by rautamiekka** [comment]
^ http://lmgtfy.com/?q=jdownloader+source+code

**Comment by Hrxn** [comment]
Which one is it? Looks all like outdated crap?

**Comment by rautamiekka** [comment]
The official doc said 'Subversion repo' and gave SVN address and ended up finding it at https://svn.jdownloader.org/projects/jd

Seems they were originally at GitHub, moved to OpenHub, then started hosting their own.

**Comment by droidberg** [comment]
so is there any fix yet for tumblr that doesnt require all this bs? anyone know of any app that can rip tumblr pages?

**Comment by cyian-1756** [comment]
@droidberg 

> so is there any fix yet for tumblr that doesnt require all this bs?

Tumblr works most of the time without needing a new api key
