### ISSUE TITLE
[Instagram] Ripper rips cropped photos

### ISSUE THREAD

**Issue by IT6uru** [4pr0n/ripme#499]
The ripper is ripping cropped photos in Instagram, at least I notice it does when the picture is cropped in the thumbnail.

**Comment by cyian-1756** [comment]
@IT6uru Can you provide a link to the album your ripped as well examples of the cropped and uncropped photos?

**Comment by IT6uru** [comment]
https://www.instagram.com/tayloralesia/


Second picture, when ripped it looks like a larger version of the thumbnail. If you open it up in instagram you get the uncropped photo. By opening in new page, viewing source and grabbing the image link, it is the full uncropped photo. Unsure as to where the ripper is pulling the link from, but that may be the key to the bug.

**Comment by cyian-1756** [comment]
@IT6uru is this https://www.instagram.com/p/BSJ4PymjDzu/?taken-by=tayloralesia the image that appears cropped? Because ripping it appears to give me the full sized version. Are you using the latest version of ripme?

**Comment by IT6uru** [comment]
I have the latest version.

**Comment by cyian-1756** [comment]
@IT6uru is this https://www.instagram.com/p/BSJ4PymjDzu/?taken-by=tayloralesia the image that appears cropped?

**Comment by IT6uru** [comment]
yes, http://tinypic.com/view.php?pic=bgtqh3&s=9. This is what I get.

**Comment by cyian-1756** [comment]
That image seems to be what IG is returning. [This image](https://scontent.cdninstagram.com/t51.2885-15/s640x640/sh0.08/e35/c0.21.1080.1080/17493629_275414326248223_6456529331400212480_n.jpg) is what IG returns when ripme tries to download https://www.instagram.com/p/BSJ4PymjDzu/?taken-by=tayloralesia.

I'm not sure what could be causing this but whatever it seems to be on IGs end. I'll do a bit more digging and see if I can find a work around that doesn't involve rewriting the whole ripper

**Comment by IT6uru** [comment]
Is the file being downloaded directly or by something that reads the image
file? Possible resolution or max file size bug? I should look at the
code.....

**Comment by cyian-1756** [comment]
> Is the file being downloaded directly

It's being download straight from that link

> Possible resolution or max file size bug?

Maybe. Might also be that IG doesn't expose full sized images to programs that don't authenticate
