### ISSUE TITLE
Rip multiply images from tweet

### ISSUE THREAD

**Issue by Norithiel** [4pr0n/ripme#500]
Hello! Ripme only saves one pic from tweet with multiple images. Is there any solution for this bug?

**Comment by IT6uru** [comment]
https://github.com/4pr0n/ripme/pull/478

**Comment by metaprime** [comment]
@Norithiel Looks like a duplicate of https://github.com/4pr0n/ripme/issues/182
@IT6uru Thanks for linking to the PR.

**Comment by metaprime** [comment]
Closing as duplicate.
