### ISSUE TITLE
Imgur: can only download 300 images

### ISSUE THREAD

**Issue by Crapmo** [4pr0n/ripme#504]
After 300 images, the program hangs.

After the 300 images, I get the following output in the console:

[!] Skipping *link* -- already attempted: /var/www/html/*folder*/*file*.*ext*
    Retrieving https://imgur.com/r/*subreddit*/new/page/10/miss?scrolled

Problem is on Imgur's side. The /page/ results after page 5/6 are the same ones from 1-5/6, just repeated.

**Comment by cyian-1756** [comment]
Can you provide an example link?

**Comment by Crapmo** [comment]
https://imgur.com/r/pics/top/page/1/miss?scrolled
https://imgur.com/r/pics/top/page/6/miss?scrolled
https://imgur.com/r/pics/top/page/11/miss?scrolled
https://imgur.com/r/pics/top/page/16/miss?scrolled
...

Repeats with same content.

You need a new way to scrape Imgur subreddit galleries.

**Comment by metaprime** [comment]
If the problem is on imgur's side there might not be anything we can do here.

**Comment by Crapmo** [comment]
Allow us to use imgur API keys and use the Imgur API for scraping, the api only returns 100 or so pages as far as I know though. Still alot of images to play with!

**Comment by Numberphile** [comment]
I had this exact same bug, here and with another ripper. I just investigated and can confirm imgur galleries repeat after the first 300 pictures. Suggest just ripping from reddit instead.

**Comment by metaprime** [comment]
@Numberphile What do you mean ripping from reddit instead? Reddit's expando for imgur albums uses JS to get the images from imgur. (Probably using the API with an API key specific to the app.) We can do the same, as @Crapmo suggested.

**Comment by Numberphile** [comment]
@metaprime I was able to get more images from just ripping from reddit.com/r/subreddit instead of imgur.com/r/subreddit. This was a while back so I don't remember if I was getting more of the imgur pictures or if it was getting bolstered by other hosting sites. My understanding here is purely experimental, my theoretical knowledge of how this thing actually works is pretty limited :/ 

Also, I seem to remember getting many more images when I first used this tool a few years ago (may have been a different ripper.)

**Comment by metaprime** [comment]
@Numberphile Okay, I see. That's a totally different thing. imgur has sections for each subreddit but a user has to intentionally post there. The way they handle rendering the images to those pages is much different from how reddit does. The reddit ripper goes through all of the links submitted to the subreddit and rips every link for which it has a ripper.
