### ISSUE TITLE
Tumblr rips reporting null

### ISSUE THREAD

**Issue by L3sb0t** [4pr0n/ripme#505]
When I try to rip from Tumblr I get an error report of "null". I've already changed the API. I'm running version 1.4.6

**Comment by droidberg** [comment]
yeah, im getting this aswell. i cant seem to get ripme to work. anyone know of a good tumblr ripper? maybe one that does video only?

**Comment by cyian-1756** [comment]
@L3sb0t What url are you trying to rip?

**Comment by L3sb0t** [comment]
beautiesfromeverywhere.tumblr.com

**Comment by cyian-1756** [comment]
@L3sb0t the link seems to be dead. The ripper just hits 404s when trying it and visiting it takes me to a login page

Is it a private tumblr? Because as far as I know ripme can't rip private tumblrs because tumblr doesn't provide api access to them

**Comment by L3sb0t** [comment]
I don't know if it's private but I tried a different tumblr and it ripped it. How can you tell the difference from private and public tumblrs?

**Comment by colourmeyellow** [comment]
I'm having the same issue, I've tried a few tumblrs and all i get is "Error: Null".  I'm running 1.4.6. Here are a few links i tried to rip https://dschroeder.tumblr.com/, https://tittiegirlharem.tumblr.com/ and http://saykiko.tumblr.com/

**Comment by cyian-1756** [comment]
@colourmeyellow It's because you're using the default ripme api key. If you make your own api key and add it to `rip.properties` you should be able to rip without issue.

to make a new api key 

You need a Tumblr account

Go here: https://api.tumblr.com/console

Click Register a new application

Fill out all required fields, etc. Just enter something

**Comment by cyian-1756** [comment]
@L3sb0t If you need to login to view the blog it's a private tumblr

**Comment by L3sb0t** [comment]
beautiesfromeverywhere.tumblr.com is a private tumblr but another blog I tried to rip but failed to, https://elraysworld.tumblr.com/ , isn't a private tumblr.

**Comment by cyian-1756** [comment]
@L3sb0t I just tried https://elraysworld.tumblr.com/ and it seems to rip fine (However I only ripped a few dozen items because I'm low on disk space)

**Comment by L3sb0t** [comment]
It's working for me now as well. Earlier I was trying to rip from history using the re-rip function but now I just typed in the url and ripped. Maybe the re-rip function has an issue?

**Comment by cyian-1756** [comment]
@L3sb0t 

> Maybe the re-rip function has an issue?

It was probably just network issues on your end

**Comment by L3sb0t** [comment]
Ok, well I'll close the issue now since all problems have been solved.
