### ISSUE TITLE
Cleanup: MinusRipper (site appears to be dead)

### ISSUE THREAD

**Issue by metaprime** [4pr0n/ripme#512]
minus.com seems to be down. Not sure if this is permanent or not. Will keep this issue around to remind me that clean up of dead rippers might be necessary.

**Comment by rautamiekka** [comment]
Judging from Google results the site has been permanently dead for at least 2 years, the domain availability at https://instantdomainsearch.com/#search=minus.com suggests it was seized, and WHOIS confirms Google owns it, so it should be safe to say minus.com ripper won't have any uses.

**Comment by metaprime** [comment]
Fixed in 036cff3a3076deb2a1b68b4a15628aa84f1ecc61
