### ISSUE TITLE
No Images Found on Hentai-Foundry

### ISSUE THREAD

**Issue by sinanjugbf** [4pr0n/ripme#515]
I put http://www.hentai-foundry.com/pictures/user/Waterproof-Pigeon into the url bar and I just get "No images found". Is there something else I'm missing?

**Comment by cyian-1756** [comment]
> Is there something else I'm missing?

Nope. The ripper is currently broken, however I made a PR that fixes it about a hour ago. The PR will hopefully be merged in within the next few hours

**Comment by metaprime** [comment]
Fixed in #481

**Comment by sinanjugbf** [comment]
it doesn't appear to be ripping the entire album. It only ripped 26 images for me, with the new update.

**Comment by cyian-1756** [comment]
> it doesn't appear to be ripping the entire album. It only ripped 26 images for me, with the new update.

What album are you trying to rip? Because the one posted in this thread only seems to have 26 images

**Comment by sinanjugbf** [comment]
I'm assuming it's because I'm logged in, but the album posted in this thread says "Displaying 1-25 of 99 results." on the first page

**Comment by cyian-1756** [comment]
>  but the album posted in this thread says "Displaying 1-25 of 99 results." on the first page

That must be something to do with your account because viewing it logged out only 26 images are in the album.

**Comment by sinanjugbf** [comment]
I see. Is there any way around that with the ripper?

**Comment by cyian-1756** [comment]
> I see. Is there any way around that with the ripper?

Not at the moment. The ripper would have to be changed to allow for logging in. You best bet would probably be to get a browser based ripper like downloadThemAll
