### ISSUE TITLE
Instagram photos are cropped!

### ISSUE THREAD

**Issue by poiuyrt546** [4pr0n/ripme#519]
Using the latest version, ALL instagram rips have cropped pics. :(

**Comment by cyian-1756** [comment]
This is a known issue with IG json interface. As IG needs JavaScript to render (Which RipMe doesn't support) the page Ripme has to use the json interface.

**Comment by poiuyrt546** [comment]
Is there a recent issue though? IG rips were basically perfect only a weeks ago.

**Comment by cyian-1756** [comment]
> Is this a recent issue though?

Nope. It's been around for at least a few weeks.

> IG rips were basically perfect only a weeks ago.

AFAIK most rips still should be, it's only image above a certain size that get cropped

What url are you trying to rip?

**Comment by poiuyrt546** [comment]
> AFAIK most rips still should be, it's only image above a certain size that get cropped
This is exactly the problem. I've noticed that image size is capped at 1080*1080. Anything above that size gets cropped. 
Is there going to be an update to fix this somehow?

**Comment by cyian-1756** [comment]
> Can this be fixed in a future update?

Not really. AFAIK there's no way to get the full sized image without java script (Which ripme doesn't support). The only thing I could think of that might solve this would be parsing the javascript for the image url which might not be possible and would be an insane pain in the ass

**Comment by JoshKastang** [comment]
My Instagram fix from 12/2016 should still be the most recent to this ripper. If you can provide me with a few image that are  being cropped examples I can probably write a fix.

**Comment by cyian-1756** [comment]
@JoshKastang 

https://github.com/4pr0n/ripme/issues/499 <-- the last thread about this bug

https://www.instagram.com/p/BSJ4PymjDzu/?taken-by=tayloralesia <-- image that is cropped

**Comment by JoshKastang** [comment]
That looks fine to me. The image rendered on screen is the same the ripper would use to download.

**Comment by cyian-1756** [comment]
@JoshKastang Are you sure? Because if you rip the IG account you can see some images ([like this](https://www.instagram.com/p/BTt7WeHle08/)) are pretty massively cropped (Her feet are almost completely cropped out in the ripped image).

**Comment by JoshKastang** [comment]
Ok, thats a better example. The other other doesn't exhibit the same symptoms.

I'll have PR submitted in a bit. It looks like IG is changing their URL structure for large images, but are forcing the 1080x1080 resolution to (probably) support legacy applications.
