### ISSUE TITLE
Please add socks5 proxy option

### ISSUE THREAD

**Issue by visualwind** [4pr0n/ripme#521]
Thank you all in advance!  
BTW, it keeps deviantart download failure

**Comment by cyian-1756** [comment]
You should be able to proxy ripme using either your system proxy settings or a tool like proxychains

>  BTW, it keeps deviantart download failure

The deviantart ripper is currently broken

**Comment by visualwind** [comment]
Can you fix this with python? I heard it is useful for rip webpage resource

**Comment by cyian-1756** [comment]
> Can you fix this with python?

Nope. Ripme is written in java

**Comment by metaprime** [comment]
I don't think ripme should directly support proxies since there are already many better tools for this. Definitely not on the radar right now.

**Comment by metaprime** [comment]
> Can you fix this with python? 

Assuming you mean the deviantART problems, there are numerous issues open and attempts to fix it. Please browse the issues and pull requests for context. It's just a matter of getting it right and releasing a fix. Stay tuned.

If you're in a hurry, you can try [this preview release](https://github.com/4pr0n/ripme/pull/516#issuecomment-298254520) which might fix the issue.
