### ISSUE TITLE
Myhentaicomics: Only rips the galleries from the first page

### ISSUE THREAD

**Issue by metaprime** [4pr0n/ripme#530]
Follow up from #476 #464 #454 

/cc @cyian-1756 

For example http://myhentaicomics.com/index.php/tag/323/Artist%3A+James+Lemay shows 1-15 of 48 and has buttons to navigate to the next page. Each of the entries on the page leads to a gallery (these galleries are ripped correctly).

We should rip all galleries from a search, including the subsequent pages of the results.

**Comment by cyian-1756** [comment]
@metaprime I'll get on fixing it this weekend, it should be pretty easily (Get total number of pages from the last button, loop over each page and download all albums from it)

**Comment by cyian-1756** [comment]
@metaprime This was fixed in pull 540 and the issue can be closed
