### ISSUE TITLE
[TRACKING] Instagram Cropping Issue

### ISSUE THREAD

**Issue by JoshKastang** [4pr0n/ripme#541]
PR #524 was submitted in an attempt to fix the JSON API response that returns a 1080x1080px cropped photo in place of the original sized image in some cases. The fix did not apply to all use cases however. I need a larger sample size of affected images to write a generalized regex.

To help expedite this process, please attach links to Instagram photos that are being cropped incorrectly when downloading. For context, this should only happen with a subset of images submitted within the past month.

**Comment by metaprime** [comment]
@JoshKastang Do you have any examples of such links already? At a minimum, pick from the case you already fixed and the case that made you realize there is still an issue.

**Comment by metaprime** [comment]
See #459 and #538

**Comment by 234908789166** [comment]
RipMe v1.4.16 downloaded the cropped version of this image posted six days ago:

https://www.instagram.com/p/BUA1mwZlKVm

**Comment by metaprime** [comment]
Appears to be fixed in https://github.com/4pr0n/ripme/pull/592

**Comment by metaprime** [comment]
Merged in https://github.com/RipMeApp/ripme/commit/c37a7c351af91b873a03c1439f92ec1431e0a11b
