### ISSUE TITLE
Queue history removal not working.

### ISSUE THREAD

**Issue by MaestroDaVinci** [4pr0n/ripme#551]
Hello i'm using this ripper for sometime now and i guess i have a problem also which i would like to have some help with.
My problem consists with the Queue, in general it's good that this functions remembers entries after you have restarted the problem, however for me it doesn't work when i'm trying to remove entries from it. 

When i open my ripper it has a Queue of 3 entries when i remove them manually every time i open the ripper again the entries are still there. For me this is an inconvenience because sometimes instead of starting a normal rip it starts a Queue entry which makes me forget about it and at a later time i try to find the rip that i wanted and i find out that it hasn't been ripped, but instead it has ripped something from the Queue. 

So my request for an issue is for this function of Queue entry removal to be working.

**Comment by rautamiekka** [comment]
1.4.16 works perfectly. What OS and Java version ?

**Comment by MaestroDaVinci** [comment]
I'm using 1.4.16 version of the RipMe ripper, on Windows 7 i don't know the version of the java. as for the path i'm using ripme.jar file to start the ripper.

**Comment by rautamiekka** [comment]
^ That's not the path, that's the filename. **For example**: `C:\Users\Administrator\Downloads\ripme.jar`

Check the Java version from _Programs and Features_, and if it's below Java SE 8 Update 131 (_8u131_), shut down everything Java, uninstall all of the old versions (except the ones you know you need, and these special cases are very rare) and install the one from http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html which matches your Win7's bit width; if the computer properties window ('System' in Control Panel or right-click on 'Computer' -> 'Properties') says 32-bit OS, you need 32-bit Java which is named x86.

**Comment by MaestroDaVinci** [comment]
Well here is my path H:\Downloads\Riping\ripme.jar
As for the java it's the latest version.

**Comment by MaestroDaVinci** [comment]
I'm closing this one, because i found out a solution to my problem.
There was a Update_ripme.bat file that was causing the problem when i deleted it, the history is able to be deleted.

**Comment by rautamiekka** [comment]
^ Which must had been gotten from an outside source.
