### ISSUE TITLE
Not really a question, just a stupid question

### ISSUE THREAD

**Issue by FriendsNone** [4pr0n/ripme#552]
Sorry for being stupid but how do you use this?

**Comment by cyian-1756** [comment]
Download the .jar from the releases page, run it and then enter the url of the album you want to rip

**Comment by metaprime** [comment]
Link from the README: https://github.com/4pr0n/ripme/wiki/How-To-Run-RipMe

**Comment by metaprime** [comment]
I'm closing this since I think the question has been sufficiently answered. Feel free to post a follow-up comment if you need additional help.
