### ISSUE TITLE
Attract attention to the project by adding to up-for-grabs.net and subreddits

### ISSUE THREAD

**Issue by metaprime** [4pr0n/ripme#556]
https://github.com/up-for-grabs/up-for-grabs.net

Use label https://github.com/4pr0n/ripme/labels/up-for-grabs

**Comment by cyian-1756** [comment]
We also might want to look into getting into the side bars/stickied posts of a few subreddits. I know that most of the adult comic subs get a few posts every month about downloading from sites that ripme supports

**Comment by metaprime** [comment]
That's a good idea. Which subreddits are you thinking of? I'll contact some mods.

**Comment by cyian-1756** [comment]
I'm thinking r/rule34, r/rule34_comics r/sex_comics and r/comics18_story

**Comment by metaprime** [comment]
Now on http://up-for-grabs.net (try searching for tag imgur). I'm realizing I should have actually included ripme as a tag. I'll make a PR to update.

**Comment by cyian-1756** [comment]
@metaprime Did you ever message those moderators?

**Comment by metaprime** [comment]
@cyian-1756 Haven't had a chance yet. What message should we send? You can also feel free and message them on our behalf.

**Comment by cyian-1756** [comment]
> What message should we send?

I was thinking something along the lines of "Hey I work on [ripme](https://github.com/4pr0n/ripme) (a open source image gallery ripper) I think the users of this sub would find useful. and was wondering if you'd link it in the side bar"

> You can also feel free and message them on our behalf.

I'll get on that

**Comment by cyian-1756** [comment]
@metaprime I sent out those PMs and so far the mods of r/sex_comics have linked ripme and the mods of r/rule34_comics have said they will

**Comment by metaprime** [comment]
@cyian-1756 Great! Thanks!

**Comment by rautamiekka** [comment]
^ I'm very happy for RipMe's success, but we all know RipMe needs a lot of refactoring it could backfire heavily instead.

**Comment by metaprime** [comment]
@rautamiekka I don't see how refactoring has anything to do with current functionality. More users = more bug reports + more people interested in helping fix bugs = fixes for bugs = better product. Whats your actual concern here?

**Comment by metaprime** [comment]
@cyian-1756 https://www.reddit.com/r/sex_comics/ has linked us in their sidebar (4pr0n/ripme which is fine because the upgrade path will enable them to get updates from ripmeapp/ripme anyway), but https://www.reddit.com/r/rule34_comics/ does not seem to have linked us. Have you heard from the others?

**Comment by cyian-1756** [comment]
> https://www.reddit.com/r/rule34_comics/ does not seem to have linked us

I'll PM them and see what's up

> Have you heard from the others?

I have not. 

We also should look into getting into the DataHoarder wiki. We also could probably get away with posting to some subreddits about open source software (r/linux comes to mind)

**Comment by metaprime** [comment]
(larger:)
https://www.reddit.com/r/opensource/
https://www.reddit.com/r/coolgithubprojects/

(smaller:)
https://www.reddit.com/r/githubprojects/

**Comment by metaprime** [comment]
By the way, since I migrated this issue over to the new repo, let's move this discussion over there.

https://github.com/RipMeApp/ripme/issues/42
