### ISSUE TITLE
Vidble albums fails to rip

### ISSUE THREAD

**Issue by shralpt** [4pr0n/ripme#562]
Attempting to rip vidble albums gives an error: 

> Failed to load https://www.vidble.com/album/xxxxxxxx after 1 attempts

(Replace xxxxxxxx with album ID)

**Comment by shralpt** [comment]
It appears to be related to an HTTPS certificate issue with vidble. Ripping from the same URL works with http:// but not https://

Attempting to save a file from vidble using wget gives:

>Resolving www.vidble.com (www.vidble.com)... 107.182.226.142
>Connecting to www.vidble.com (www.vidble.com)|107.182.226.142|:443... connected.
>ERROR: The certificate of ‘www.vidble.com’ is not trusted.
>ERROR: The certificate of ‘www.vidble.com’ hasn't got a known issuer.

So, a workaround might be to use the regular http connection. Unfortunately, when you rip a user profile from reddit, vidble links default to https.

**Comment by cyian-1756** [comment]
> ERROR: The certificate of ‘www.vidble.com’ is not trusted.

> ERROR: The certificate of ‘www.vidble.com’ hasn't got a known issuer.

This might be an issue on your end. COMODO CA Limited (The issuer for vidble) is trusted on my PC.

Can you post a test link?

**Comment by cyian-1756** [comment]
Testing with this link https://www.vidble.com/album/sQEMXFue 

ripme seems to work fine even with https, so it just seems that COMODO CA Limited isn't trusted on your computer

**Comment by metaprime** [comment]
Web page loads fine for me but the ripper fails with something resembling a cert error. I'll try it again after updating java, but cert authorities have breaches and loss of trust all the time, and various root certs remove trust in them.

Here's the log from the console (more detailed than the one in the GUI): [log.txt](https://github.com/4pr0n/ripme/files/1055955/log.txt)

Anyway what if we forced http for this site and just ignored the https cert altogether?

**Comment by metaprime** [comment]
In fact, we don't force https, so if you use an http URL, the site rips fine:

```
>java -jar ripme.jar -u http://www.vidble.com/album/sQEMXFue
Loaded C:\dev\ripme\rip.properties
Loaded log4j.properties
Initialized ripme v1.4.19
Retrieving http://www.vidble.com/album/sQEMXFue
    Downloading file: http://www.vidble.com/ktFsjTqAbu.jpg Retry #1
    Downloading file: http://www.vidble.com/3BB3trFRXd.jpg Retry #1
    Downloading file: http://www.vidble.com/Hm4q0sq4ir.jpg Retry #1
    Downloading file: http://www.vidble.com/7MveFlkDaZ.jpg Retry #1
    Downloading file: http://www.vidble.com/JNNI4yVExF.jpg Retry #1
[+] Saved http://www.vidble.com/ktFsjTqAbu.jpg as .\rips\vidble_sQEMXFue\001_ktFsjTqAbu.jpg
    Downloading file: http://www.vidble.com/nIN9B3jh8T.jpg Retry #1
[+] Saved http://www.vidble.com/nIN9B3jh8T.jpg as .\rips\vidble_sQEMXFue\006_nIN9B3jh8T.jpg
[+] Saved http://www.vidble.com/JNNI4yVExF.jpg as .\rips\vidble_sQEMXFue\005_JNNI4yVExF.jpg
[+] Saved http://www.vidble.com/7MveFlkDaZ.jpg as .\rips\vidble_sQEMXFue\004_7MveFlkDaZ.jpg
[+] Saved http://www.vidble.com/3BB3trFRXd.jpg as .\rips\vidble_sQEMXFue\003_3BB3trFRXd.jpg
[+] Saved http://www.vidble.com/Hm4q0sq4ir.jpg as .\rips\vidble_sQEMXFue\002_Hm4q0sq4ir.jpg
```

**Comment by cppsse** [comment]
I found a workaround for this issue.  You have to import the Vidble certifcate into your keystore where java runs.

1.  Open https://vidble.com in your browser.  Click on the lock sign and export the certificate.  Should be named 'vidblecom.crt'

2.  Run 'keytool -import -noprompt -trustcacerts -alias vidblecom -file vidblecom.crt -keystore /etc/ssl/certs/java/cacerts'

Where 'cacerts' is the keystore on your system. 

Password is 'changeit'

**Comment by metaprime** [comment]
Using http links is also a workaround, and a fair bit simpler. :)

**Comment by metaprime** [comment]
Anyway, this is not something ripme can fix directly. There are multiple workarounds in this thread. Closing this issue.
