### ISSUE TITLE
Instagram fails to rip if the account has a short name, such as 2 or 3 characters long.

### ISSUE THREAD

**Issue by anonCoder123** [4pr0n/ripme#564]
I noticed that ripme will fail to recognize an Instagram URL as valid if the account name is particularly short.

My first thought was that the account was private, but then I found a public account that had a short account name as well, and it fails also.

Here is an example of a public account that fails: https://www.instagram.com/ch/

I haven't looked at the code yet, but I imagine there is some type of conditional that expects the account name to be longer than 2 or 3 characters.

**Comment by cyian-1756** [comment]
It looks like the error is in `sanitizeURL` which uses the regex `"^.*instagram\\.com/([a-zA-Z0-9\\-_.]{2,}).*$"`. Changing it to `"^.*instagram\\.com/([a-zA-Z0-9\\-_.]{1,}).*$"` seems to fix the issue.

I'll do some testing and make a pull later on today

**Comment by rautamiekka** [comment]
^ Just change `{2,}` to `+` then, no point in using `{1,}`.

**Comment by metaprime** [comment]
Fixed by #569
