### ISSUE TITLE
Imagebam gallery links no longer work

### ISSUE THREAD

**Issue by bamtan** [4pr0n/ripme#570]
Running the latest version (1.4.19), it detects the Imagebam link, but fails to start downloading. 

Log:
`Failed to load http://www.imagebam.com/gallery/xxxxxxxxxxxxxxxxxxxx after 1 attempts`

**Comment by cyian-1756** [comment]
Can you post the link you were trying to rip?

**Comment by bamtan** [comment]
Seems to be working now, can't find the link I was trying to scrape.

If I run across this issue again I'll post the link as well.
