### ISSUE TITLE
The 'Save album titles' checkbox

### ISSUE THREAD

**Issue by rautamiekka** [4pr0n/ripme#571]
What's the plan with it ? Looking at DA ripper, it's absolutely not referenced and other files, not just rippers, make unclear references.

DA folders are ripped with the folder owner's name, whether it's gallery, favs or scraps, and the folder's ID. Instead of this kinda name it'd be better if the folder's complete name was used instead. I can help with that.

**Comment by cyian-1756** [comment]
> What's the plan with it ? Looking at DA ripper, it's absolutely not referenced

AFAIK it was never implemented in the DA ripper.

> and other files, not just rippers, make unclear references.

Ripme in a nutshell. Someone really needs to get on documenting everything.

**Comment by taligregor** [comment]
can i take a stab at this?

**Comment by cyian-1756** [comment]
@taligregor Sure
