### ISSUE TITLE
'Autorip from Clipboard' option discards the first entry

### ISSUE THREAD

**Issue by rautamiekka** [4pr0n/ripme#572]
Tested in 1.4.19 (644324090102c51c8a47b232504ce808f0d1511a), the first entry in your clipboard is always discarded regardless of whether it's an actual address and regardless of whether it's a supported address. Having a dummy line for the sole purpose of being discarded works around it.

If it makes any difference, it's a Window$ 7 Ultimate SP1 x64 with Oracle Java SE Development Kit 8 Update 131 x64.

For example: from this list the first, `http://rautamiekka.deviantart.com/gallery/`, is discarded and the rest added:
```
http://rautamiekka.deviantart.com/gallery/
http://rautamiekka.deviantart.com/gallery/52116956/PHOTOS-cats-Rontti
http://rautamiekka.deviantart.com/gallery/34326766/PHOTOS-cats-Miru
http://rautamiekka.deviantart.com/gallery/34326811/PHOTOS-cats-Monni
```
, but this list's addresses are perfectly added:
```

http://rautamiekka.deviantart.com/gallery/
http://rautamiekka.deviantart.com/gallery/52116956/PHOTOS-cats-Rontti
http://rautamiekka.deviantart.com/gallery/34326766/PHOTOS-cats-Miru
http://rautamiekka.deviantart.com/gallery/34326811/PHOTOS-cats-Monni
```

**Comment by cyian-1756** [comment]
I'm running 1.4.19 on Ubuntu 16.04 with openjdk and can't repo this bug. 

My OpenJDK info is 

openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

**Comment by metaprime** [comment]
I think I repro'd this on Windows 10, but honestly this autorip feature is pretty confusing. My guess is that it has to do with Windows line endings. This will probably be a simple fix once we figure out where the problem is.

**Comment by rautamiekka** [comment]
Can't repro either. Possibly Win7 or another program having run for long enough without reboots causing it.
