### ISSUE TITLE
Xhamster gallery ripper not working 2017-06-09

### ISSUE THREAD

**Issue by zorb123** [4pr0n/ripme#575]
I updated to v1.4.19 and it stopped ripping Xhamster galleries. It was working fine before this update. Can someone please fix this. Really appreciate.
Thanks.
P.S. Please add xvideos gallery ripper.

**Comment by rautamiekka** [comment]
If the previous version wasn't 1.4.18, download each version between the previous one and 1.4.19 and try.

Don't ask for different things in same ticket.

**Comment by jimbotomato** [comment]
XHamster changed their gallery URL format so Ripme doesn't detect it anymore.

**Previously:**
xha*****.com/photos/gallery/<numbers>/<name>.html

**Now:**
xha******.com/photos/gallery/<name>-<numbers>

**Comment by grml32** [comment]
I get the message "No Compatible ripper found".
Not working anymore at all in xhamster :-(

**Comment by metaprime** [comment]
Fixed in https://github.com/RipMeApp/ripme/commit/cfab32d271f3afefa4e9c102070fddee268f649a
