### ISSUE TITLE
Tumblr rips reporting null

### ISSUE THREAD

**Issue by L3sb0t** [4pr0n/ripme#576]
When I try to rip from Tumblr, I get a null error message. I've had this problem before but fixed it by changing the API in the properties file but I think an update deleted my properties file since it suddenly disappeared. How can a get a new properties file?

**Comment by cyian-1756** [comment]
> How can a get a new properties file?

Just run ripme and a new properties file should be made

**Comment by L3sb0t** [comment]
I retried the ripper and it didn't make a new properties file but it did start ripping. Does it still use the API I used from Tumblr before? I'm asking because I don't want to keep bothering you with these Tumblr issues.

**Comment by Hrxn** [comment]
Checked your Home dir?
And yes, it still uses the API afaik.

**Comment by L3sb0t** [comment]
It's reporting null again

**Comment by metaprime** [comment]
@L3sb0t is this resolved now?
