### ISSUE TITLE
1.4.20 Broke downloads pretty much entirely, only downloading a few items

### ISSUE THREAD

**Issue by Davrial** [4pr0n/ripme#580]
I downloaded 1.4 yesterday and downloaded a few of my favorite artist's DA and Tumblr page. I went to set downloads to run while I was sleeping, but there was an update available, so I updated. Then I went to set my downloads, and each download, despite being of large albums, finished after 10 items or less. What gives? Going to backdate.

**Comment by Davrial** [comment]
Additionally, I cannot completely uninstall the new version of the jar. Even ending the process TREE I was still unable to delete the .jar. To backdate and use the same folder I had to name the new jar ripme1.jar

**Comment by Davrial** [comment]
Correction: I have tested with albums I have already downloaded and moved elsewhere. Nothing is downloading now. Instead, it spits out "download complete" then a red "Null", and that's it. No clue what is causing this, even moved folders and redownloaded the old jar

**Comment by cyian-1756** [comment]
What urls are you trying to download?

**Comment by rautamiekka** [comment]
Works perfectly for me when I tried a favs folder of mine. Are you using Oracle Java SE 8 Update 131 which has same bit width as your OS ?

Are you on Window$ 10 ? In which case it's not a surprise, that piece of shit is either broken or very broken.

If you're on Window$, start Command Prompt as Admin and run this to force shut down regardless of stuck processes (still not guaranteed):

```batch
shutdown /s /t 0 /f
```

On Linux, BSD and other NIX systems you shouldn't need any commands to shut down even if a process is stuck unless it's a very important one; as `root` run `shutdown now`.

**Comment by Davrial** [comment]
I downloaded multiple Tumblr and Deviant Art pages on the first non-error'd run. The one I used as a test once I saw downloads were failing was http://deadbones5.tumblr.com/ . Again, what it's doing now is spitting out "download complete" and then "null" after only seconds and without downloading anything. All URLs are doing this now.

As for Windows, I am indeed using Windows 10. As for Java, I dont know what version I was on, but it was working fine initially. I did not update my Java but the errors started anyway, and updating my Java didnt fix it

**Comment by Davrial** [comment]
Tested with a deviant art site and it seems to be working? The first deviant art i tested only downloaded 10 and then errored as well though.

**Comment by Davrial** [comment]
I cleared my Java installs and reinstalled and rebooted, tested the DA site that failed before and it's working. Tumblr still broken but that's a single issue not widespread like I initially had so I'll close this

**Comment by rautamiekka** [comment]
Updated my post.

**Comment by metaprime** [comment]
@rautamiekka As a matter of being helpful, unless there's some evidence that Windows is fundamentally at fault for something, let's avoid blaming the OS and try to help users come to a resolution. In my experience, Java is just as likely to be inexplicably broken on any platform.
