### ISSUE TITLE
The queue dont work

### ISSUE THREAD

**Issue by webtoria** [4pr0n/ripme#581]
I have a problem with the queue, and it does not advance me. I close and reopen and always pick only the first but never advance beyond the first of the queue

The links are from albums imgur

**Comment by rautamiekka** [comment]
We need more data. 'Latest' ain't valid.

1) The links you tried, regardless of whether they worked in any way.
2) What OS and release ?
3) What Java release ?
4) What RipMe release ?

**Comment by webtoria** [comment]
Windows 10, RipMe 1.4.19

**Comment by rautamiekka** [comment]
Updated my post with instructions for Java version fetching.

**Comment by webtoria** [comment]
1.8.0_91

**Comment by rautamiekka** [comment]
91 is old, 131 is newest. http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html is where you can get the newest.

First uninstall all previous Java versions to avoid any problems, which are more than plentiful on Win10, then install the new one.

**Comment by metaprime** [comment]
@rautamiekka Can we keep the hate language out of threads trying to help users with a problem? Regardless of your personal or others' experience with a platform, the platforms continue to exist and be supported by this app. Simply do your best to help understand and resolve users problems on whatever platform they are on. Thank you.

**Comment by webtoria** [comment]
The problem has not been fixed

**Comment by cyian-1756** [comment]
What urls are you trying to rip?

**Comment by metaprime** [comment]
Not enough information here to take action. Closing this issue. If you have another issue, please open a new issue and provide all information requested in the template.
