### ISSUE TITLE
Dead code in ImgurRipper

### ISSUE THREAD

**Issue by cyian-1756** [4pr0n/ripme#583]
Looking over the imgur ripper there seems to be a lot of dead code. For example [this JSON ripping block doesn't work and I doubt it has for a while](https://github.com/4pr0n/ripme/blob/2ff45e8696878783072f79dad8988d18ea8eb749/src/main/java/com/rarchives/ripme/ripper/rippers/ImgurRipper.java#L222)

~~There's also this [/noscript fallback](https://github.com/4pr0n/ripme/blob/2ff45e8696878783072f79dad8988d18ea8eb749/src/main/java/com/rarchives/ripme/ripper/rippers/ImgurRipper.java#L222) which as far as I know hasn't worked in over a year~~ It looks like the noscript fallback works, I could've sworn the imgur removed it last year

**Comment by metaprime** [comment]
Yes, I wouldn't be surprised if we've got a ton of dead code. I approve removing it. Just ensure there are no regressions in `mvn test`

**Comment by metaprime** [comment]
Looks to be closed in ripmeapp/ripme#6
