### ISSUE TITLE
Ubuntu Mate: Exception in thread "main" error

### ISSUE THREAD

**Issue by Mutini** [4pr0n/ripme#589]
My environment:

VMWare Workstation Virtual Machine
Ubuntu Mate 16.04.2 LTS  x64 (latest updates)
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
Maven 3.3.9-3

I'm able to run RipMe 1.2.13 perfectly fine.

I can't run ripme 1.4.21 (can't run any 1.4 version). I get the following error(any ideas?)...

Initialized ripme v1.4.21
Exception in thread "main" java.lang.UnsupportedOperationException
	at java.awt.TrayIcon.<init>(TrayIcon.java:144)
	at java.awt.TrayIcon.<init>(TrayIcon.java:168)
	at com.rarchives.ripme.ui.MainWindow.setupTrayIcon(MainWindow.java:947)
	at com.rarchives.ripme.ui.MainWindow.createUI(MainWindow.java:250)
	at com.rarchives.ripme.ui.MainWindow.<init>(MainWindow.java:164)
	at com.rarchives.ripme.App.main(App.java:51)

**Comment by rautamiekka** [comment]
Although OpenJDK and Oracle Java should be the same thing, that might be the reason cuz I'm running Oracle Java of same version and same bit width as OS on Lubuntu 16.04.2 LTS x86 with RipMe 1.4.21 which runs as perfectly as it does on Window$ 7 Ultimate SP1 x64.

Since you're on Ubuntu, try uninstalling OpenJDK, then follow these to install Oracle JDK (JRE ain't provided by the repo, for less work):

1) In the repo management window add `ppa:webupd8team/java` to the repos.
2) Install these packages:

```
oracle-java8-installer oracle-java8-set-default oracle-java8-unlimited-jce-policy
```

For completeness, the packages are:
- auto-installer/updater for the JDK (whenever a new release is out, updating this package does the rest)
- ensure this Java is made the default
- enable Java Cryptography Extension to use the best encryptions available

**Comment by Mutini** [comment]
> Since you're on an Ubuntu, try uninstalling OpenJDK, then follow these to install Oracle JDK (JRE ain't provided by the repo, for less 

Thanks for the reply.

I did what you instructed.

My new Java Version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Problem still occurs. I get the same error as posted above upon running 1.4.21, however I have no problem running version 1.2.13.

**Comment by rautamiekka** [comment]
Yeah, it certainly starts sounding like Ubuntu Mate issue, as I feared at first.

**Comment by metaprime** [comment]
> I get the same error as posted above upon running 1.4.21, however I have no problem running version 1.2.13.

We should look into what changed since. The only funny business with the app (outside of simply adding rippers and other minor changes) was a fix to prevent crashing on Windows 10 CU (1.4.12). Can you definitely not run 1.4.11?

Can you run version 1.3.0?

**Comment by rautamiekka** [comment]
Can't repro; booted Ubuntu MATE 16.04.2 LTS x64 live from USB stick and installed Oracle Java the same way I instructed but RipMe 1.4.21, 1.5.0 and 1.5.1 run just fine.

Not sure if this is a configuration issue or a failed upgrade, but on a fresh system no problem.

**Comment by Mutini** [comment]
I'm totally at a loss as to why my Ubuntu Mate virtual machine is behaving like this.

I went and downloaded the ripme.jar from git-hub for 1.4.11 and 1.3.0, and ran them from my download folder, and they worked. Then I stared downloading jar builds to see where it might be broken, but it started them all, right up to the current build.

Then, I went back to my clone directory, and tried to run the build I compiled, and it wouldn't work. But here's is where it gets strange. After I ran the compiled build, I then tired the other downloaded build, and it stopped working.

Something must be wrong in the manner this virtual machine was installed. Though, I tried it on 3 fresh VM's and they all behaved the same. Could be a bug with VMWare Workstaion and the way it's installing the VM.

Thanks for all the help.

**Comment by rautamiekka** [comment]
^ If you can afford the effort you could try with Oracle VirtualBox. It's not much different from how VMware Workstation is installed, unless VMware changed the procedure.

**Comment by Mutini** [comment]
Thanks for the suggestion, though  I prefer VMWare. It's on the fly image restoration, and hardware emulation are just leaps and bounds better then VirtualBox, IMO. I'll just download the ripme.jar for now, and see if the issue resolves itself in future updates.

**Comment by metaprime** [comment]
If the official downloads are working for you but not the ones you build on your own, it's probably a Java build tools problem.

Good to know you can use the official builds! I'll close this now.

**Comment by Mutini** [comment]
Well, I figured out why I was getting that error. You'll love this.

The error was being thrown, because I deleted the Notification Area object from the toolbar panel.

When I added the Notification Area object back to the toolbar panel, RipMe's current version started working again.

This only affected certain builds of RipMe. The older builds, such as 1.3 and 1.2 were unaffected by this.

**Comment by rautamiekka** [comment]
^ In other words the tray icon part should be made optional by `try ... catch`.

**Comment by metaprime** [comment]
Thanks! Sounds like we understand the problem so I'm reopening this.

**Comment by zaywolfe** [comment]
I'm getting this same error in Elementary OS with v1.5.2. Notification area isn't disabled though. Also this is the latest release jar not something I'm compiling. 

$ java -jar ripme.jar 
Initialized ripme v1.5.2
Exception in thread "main" java.lang.UnsupportedOperationException
	at java.awt.TrayIcon.<init>(TrayIcon.java:144)
	at java.awt.TrayIcon.<init>(TrayIcon.java:168)
	at com.rarchives.ripme.ui.MainWindow.setupTrayIcon(MainWindow.java:947)
	at com.rarchives.ripme.ui.MainWindow.createUI(MainWindow.java:250)
	at com.rarchives.ripme.ui.MainWindow.<init>(MainWindow.java:164)
	at com.rarchives.ripme.App.main(App.java:51)

**Comment by rautamiekka** [comment]
@zaywolfe Make your own ticket.

**Comment by Mutini** [comment]
@zaywolfe are you sure you have the Notification Area added to your desktop panel?

I'm running Ubuntu Mate, and get the same error you're reporting. If I add the Notification Area to my desktop toolbar panel, then RipMe (latest version) works perfectly fine, without the Notification Area added I get the error you listed.

I posted a screenshot showing the Notification Area item you need to have activated.

http://i.imgur.com/u8Zaggi.png

**Comment by zaywolfe** [comment]
@Mutini 

Pretty sure. Here's a screenshot to be sure. But then this is Elementary OS and they like to modify things everyone else already has so they can be special. But then it makes it all act odd when programs expect it to act like the same way all the others do.

**Comment by Mutini** [comment]
@rautamiekka you might just have a volume indicator on your panel. Right click the panel, and see if you can add "Notification Area" object to your panel. Then try RipMe to see if you get the error.

**Comment by rautamiekka** [comment]
@zaywolfe I were thinking it could be similar but not the same, hence new ticket.

**Comment by metaprime** [comment]
@rautamiekka @zaywolfe I'd say this is substantially similar that there's no need to clutter the issue tracker with another ticket. Unless we fix one and see that it hasn't fixed the other related issue reported here, or otherwise prove it's different, we should keep it to one issue.

**Comment by rautamiekka** [comment]
^ True.

**Comment by rautamiekka** [comment]
I'm sorry for the spam, I'm just not really understanding GitHub, in an effort to avoid using Git's commands ...

**Comment by metaprime** [comment]
Fixed

**Comment by cinnamonbubblegum** [comment]
I just downloaded 1.5.0 and got the same error:
```
[USER@pc TMP]$ java -jar ./ripme.jar
Loaded file:/home/USER/TMP/ripme.jar!/rip.properties
Loaded log4j.properties
Initialized ripme v1.5.0
Exception in thread "main" java.lang.UnsupportedOperationException
	at java.desktop/java.awt.TrayIcon.<init>(TrayIcon.java:145)
	at java.desktop/java.awt.TrayIcon.<init>(TrayIcon.java:169)
	at com.rarchives.ripme.ui.MainWindow.setupTrayIcon(MainWindow.java:947)
	at com.rarchives.ripme.ui.MainWindow.createUI(MainWindow.java:250)
	at com.rarchives.ripme.ui.MainWindow.<init>(MainWindow.java:164)
	at com.rarchives.ripme.App.main(App.java:51)
```

OS: Manjaro Linux x86_64 
Kernel: 4.19.62-1-MANJARO 
DE: GNOME 3.32.2 
WM: GNOME Shell 
openjdk 12.0.2 2019-07-16
OpenJDK Runtime Environment (build 12.0.2+10)
OpenJDK 64-Bit Server VM (build 12.0.2+10, mixed mode)

**Comment by cyian-1756** [comment]
@pornismuybae This branch of ripme is unmaintained. You can download the latest version at https://github.com/RipMeApp/ripme/releases
