### ISSUE TITLE
Couldn't download the entire gallery from Deviantart

### ISSUE THREAD

**Issue by Romangelo** [4pr0n/ripme#594]
Some galleries have hundreds of images but RipMe downloaded only the first 24 or 48 or 96 images, and says that it's completed.

**Comment by rautamiekka** [comment]
Is this problem still alive ?

**Comment by rautamiekka** [comment]
Is this problem still alive ? Cuz I left a fresh installation of Win7 Ultimate SP1 x64, Oracle Java SE 8 Update 131 x64 and RipMe 1.5.2 get 3 galleries (2 were 99.999% ripped already, though) having well over 100 uploads each over night and got them no problem.

Next time fill out the template as instructed.

**Comment by Romangelo** [comment]
just tried it again today and it's working just fine. not sure what was the problem back then.
