### ISSUE TITLE
Ill pay  anyone who can make a working rip for http://thefappeningblog.com/

### ISSUE THREAD

**Issue by Rmalone66** [4pr0n/ripme#596]
Ripme version:1.5.2
Java version (v8 131):
Operating system:windows 10
http://thefappeningblog.com/
i need the rip to download the images from all the album inside not just the preview thumbnails
e.ghttp://thefappeningblog.com/category/jennifer-lawrence/

**Comment by rautamiekka** [comment]
Absolutely pointless double-posting ...

**Comment by Rmalone66** [comment]
Thought someone might see it here rather than the other thread since no one accepted it

**Comment by Rmalone66** [comment]
Would you be interested in doing it?

**Comment by rautamiekka** [comment]
^ It's not about the interest, but the skill. That's not to say it would be impossible for me, but saying it's guaranteed would be a big lie.

**Comment by Rmalone66** [comment]
I mean if you want to try it I'll be grateful and pay you

**Comment by metaprime** [comment]
This issue is open at https://github.com/RipMeApp/ripme/issues/27 -- closing this one since the issue tracker will be moving over.
