### ISSUE TITLE
All imgur albums are error reporting.

### ISSUE THREAD

**Issue by Smoreonastick** [4pr0n/ripme#597]
* Ripme version: v1.5.7
* Java version (output of `java -version`): 1.8.0_131
* Operating system: Win 10
* Exact URL you were trying to rip when the problem occurred: All IMGUR albums
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Detail the expected behavior here.

## Actual Behavior

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

**Comment by rautamiekka** [comment]
Works perfectly for me. You're making it too hard by omitting the errors, but I'm confident they were errors you didn't understand.
