### ISSUE TITLE
Ripper requests: archived.moe, archiveofsins.com, fetlife

### ISSUE THREAD

**Issue by oldesoul95** [4pr0n/ripme#599]
Feature request - ripping support for threads from:

https://archived.moe/soc/thread/25537505/#q25537505 (example)
https://archiveofsins.com/soc/thread/25548343/#25548343 (example)

Seems similar to 4chan so possibly not too involved?

Also the ability to rip pictures from Fetlife? Using Chrome to inspect every picture individually and open in new tabs is obnoxious.

**Comment by metaprime** [comment]
https://github.com/RipMeApp/ripme/issues/38
