### ISSUE TITLE
8muses gives null error on large downloads

### ISSUE THREAD

**Issue by DinnerBlasterX** [4pr0n/ripme#602]
[NSFW]
* Ripme version: 1.5.14
* Java version (output of `java -version`): 1.7.0_55
* Operating system: Windows 10
* Exact URL: anything really large (ex: https://www.8muses.com/comix/album/taboolicious_xxx-comics)
* Please include any additional information about how to reproduce the problem:  Attempt to download an album with a few hundred (or thousand) images and eventually the program will give the error.

## Expected Behavior

Downloads all the albums in an 8muses artists page and puts them in the download directory.

## Actual Behavior
Says 'rip complete' then Error: 'null' if the amount of items being downloaded is too large, then deletes the folder that was created in the download directory.

I would assume this may be an API thing, or something to do with too many requests.  It may also be based on the number of albums rather than number of images, but it's difficult to tell.  Downloads work fine in the 0-400 image range on a few albums, but don't seem to work for the same amount of images in 20-30 albums (some of which are inside other directories).

Note that it is possible to save all the same images from an artist by queuing the albums individually.

**Comment by rautamiekka** [comment]
Please go report at the new repo at https://github.com/ripmeapp/ripme/
