### ISSUE TITLE
Ripping Reddit users is not ripping all of their stuff. 

### ISSUE THREAD

**Issue by Smoreonastick** [4pr0n/ripme#603]
* Ripme version: 1.5.15
* Java version (output of `java -version`): (build 1.8.0_151-b12)
Java HotSpot(TM) Client VM (build 25.151-b12, mixed mode, sharing)
* Operating system: Win 10 64bit
* Exact URL you were trying to rip when the problem occurred: https://www.reddit.com/user/kawaiiikitty
* Please include any additional information about how to reproduce the problem:
A lot of users aren't having their non reddit/imgur sources ripped properly. 
## Expected Behavior
To rip all links submitted
## Actual Behavior
Misses a lot of links.

**Comment by cyian-1756** [comment]
Hey, this is the old (And basically abandoned) repo. You should resubmit this over at https://github.com/ripmeapp/ripme

On the issue itself the ripper only rips from a few select sites, if you can give me the sites that the ripper doesn't rip from I can see if I can add support for them

**Comment by metaprime** [comment]
https://github.com/RipMeApp/ripme/issues/174

**Comment by metaprime** [comment]
https://github.com/RipMeApp/ripme/issues/90
