### ISSUE TITLE
instagram rips do not save

### ISSUE THREAD

**Issue by supersubb** [4pr0n/ripme#605]
* Ripme version: 1.6.11
* Java version (output of `java -version`): 1.8.0_144
* Operating system:Windows 7
* Exact URL you were trying to rip when the problem occurred:instagram.com/ximenacordoba
* Please include any additional information about how to reproduce the problem:

## Expected Behavior
files get saved in the directory.

## Actual Behavior
0 kb files named with a date and serial number are saved instead of the actual images, it seems to be because there is an invalid character for windows - ":" (colon) that is getting inserted in the file name.
log snippet:
Downloading https://instagram.fhyd2-1.fna.fbcdn.net/t51.2885-15/sh0.08/e35/11850298_937463139630973_44990691_n.jpg
Downloading https://instagram.fhyd2-1.fna.fbcdn.net/t51.2885-15/sh0.08/e35/11849190_1193337747361092_52069880_n.jpg
Downloaded G:\ncache\rips\instagram_ximenacordoba\2015_09_14_12:07_11850298_937463139630973_44990691_n.jpg
Downloaded G:\ncache\rips\instagram_ximenacordoba\2015_09_13_10:43_11849190_1193337747361092_52069880_n.jpg

**Comment by metaprime** [comment]
Moved to RipMeApp/ripme
