### ISSUE TITLE
Support for GAB.AI

### ISSUE THREAD

**Issue by rudolphos** [4pr0n/ripme#608]
Can support for gab.ai be added?

Sample account URL: https://gab.ai/a

Sample image URL: https://gabfiles.blob.core.windows.net/image/5a1aed1cbacf6.jpeg

Sample video URL: https://gab.ai/tv/watch/2855

**Comment by cyian-1756** [comment]
@rudolphos This is the old and unmaintained repo, remake this issue at https://github.com/RipMeApp/ripme which is the maintained repo

**Comment by metaprime** [comment]
Tracking in https://github.com/RipMeApp/ripme/issues/38
