### ISSUE TITLE
Design sites?

### ISSUE THREAD

**Issue by epicradness** [4pr0n/ripme#609]
Wondering if it's possible to include some portfolio/design/art-centric sites like Behance and Dribbble. 

Examples:

https://dribbble.com/typogriff

https://www.behance.net/illuleo

Thanks!  Looking to buy some coffee/beer for the added support on this req too!  Good job on everything so far team!!!

**Comment by metaprime** [comment]
Moved to https://github.com/RipMeApp/ripme/issues/320. Thanks @epicradness
