### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by dante25** [4pr0n/ripme#82]
Hi friend, I liked this useful tool but everytime when you release new update something not work. As I said last time flickr can't be ripped, I wanted to download some galleries from deviantART but it says "No images found" (also favorites not supported). I'm sorry to say this but it really become useless. For me Ripme worked the best in 1.0.20 -1.0.40 versions.

About deviantART, I've tried "deviantART favorite downloader" and it's very good but the big problem is that very often connection breaks down. Maybe you can use some code from this downloader to improve your app.

**Comment by optozorax** [comment]
Hello. Thanks for program. This program can`t download from favourites gallery, example: http://black-b-o-x.deviantart.com/favourites/62135389/Pixel-Art . Next example: http://shanineko.deviantart.com/favourites/44910823/TUTORIAL.
