### ISSUE TITLE
Req Site : http://en.2dgalleries.com

### ISSUE THREAD

**Issue by singhs-apps** [4pr0n/ripme#96]
Hello,

It will be wonderful if Ripme supports this wonderful art site : http://en.2dgalleries.com

Thanks

**Comment by singhs-apps** [comment]
doesn't work anymore

**Comment by rautamiekka** [comment]
Confirmed not working anymore, but we should move this to https://github.com/ripmeapp/ripme/:

```
Downloading http://www.2dgalleries.com/artist/jean-giraud-4092
Rip complete, saved to G:\_DOWNLOADS_\RipMe\rips\2dgalleries_jean-giraud-4092
null
```
Takes a few seconds on 'Downloading', then says complete and null.

Window$ 7 Ultimate SP1 x64
Oracle Java SE 8 Update 152 x64
RipMe 1.6.2

**Comment by metaprime** [comment]
https://github.com/RipMeApp/ripme/issues/117
